apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eli-start-epik8s-deploy
  namespace: argocd
  labels:
      deploy: eli
spec:
  project: default
  source:
    repoURL: 'https://github.com/infn-epics/epik8s-chart.git'
    path: deploy
    targetRevision: main
    helm:
      values: |
          namespace: eli
          domain: "int.eli-np.ro"
          ingressClassName: "haproxy"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: eli
  syncPolicy:
    automated:
      prune: true  # Optional: Automatically remove resources not specified in Helm chart
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
      - Prune=true