apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eli-start-epik8-deploy
  namespace: argocd
  labels:
      deploy: eli
spec:
  project: default
  source:
    repoURL: 'https://baltig.infn.it/lnf-da-control/epik8-eli.git'
    path: deploy
    targetRevision: HEAD
    helm:
      values: |
          namespace: backend
          domain: "apps.k8s-da.lnf.infn.it"
          ingressClassName: "haproxy"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: eli
  syncPolicy:
    automated:
      prune: true  # Optional: Automatically remove resources not specified in Helm chart
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
      - Prune=true