# yaml-language-server: $schema=../schemas/technosoft.ibek.ioc.schema.json

ioc_name: tmlgun
description: tmlgun

shared:
  - &motor
    type: motorTML.motorAxis
    controller: TML
    NSTEPS: 200
    NMICROSTEPS: 256
    VELO: 20
    VELO_MAX: 50
    VELO_MIN: 0.1
    ACCL: 0.5
    ACCL_MAX: 1.5
    ACCL_MIN: 0.01
    HAR: 0.5
    HVEL: 10
    JAR: 1
    JVEL: 5
    EGU: "ustep"
    SLSP: 0.8
    ENABLED: 1
    TIMEOUT: 0

entities:
  - type: motorTML.CreateController
    controllerName: TML
    P: "SPARC:TML:CH1"
    TTY: /var/tmp/ttyV0
    numAxes: 11
    hostid: 5

  - <<: *motor
    axid: 3
    CHANNEL_ID: AC1FLG01

  - <<: *motor
    axid: 4
    CHANNEL_ID: AC2FLG01
  - <<: *motor
    axid: 5
    CHANNEL_ID: AC3FLG03

  - <<: *motor
    axid: 10
    CHANNEL_ID: GUNFLG01
  - <<: *motor
    axid: 8
    CHANNEL_ID: GUNHOR01
  - <<: *motor
    axid: 7
    CHANNEL_ID: GUNVER01
  
  - <<: *motor
    axid: 11
    CHANNEL_ID: DGLFLG00

  - <<: *motor
    axid: 23
    CHANNEL_ID: AC1BAM01

  - <<: *motor
    axid: 12
    CHANNEL_ID: UTLFLG01

  - <<: *motor
    axid: 13
    CHANNEL_ID: UTLFLG02

  - <<: *motor
    axid: 14
    CHANNEL_ID: DGLFLG01