{
 "title": "Modulatori",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "IONPUMP (nA)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "target": "LEL:MOD:SCAT:MOD01:IONPMP:R_RB" },
    { "target": "LEL:MOD:SCAT:MOD02:IONPMP:R_RB" },
    { "target": "LEL:MOD:SCAT:MOD03:IONPMP:R_RB" },
    { "target": "LEL:MOD:SCAT:MOD04:IONPMP:R_RB" }
   ]
  },
  {
   "title": "SOLENOID TEMPERATURE ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "target": "LEL:MOD:SCAT:MOD01:SOLPS:TEMP_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD02:SOLPS:TEMP_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD03:SOLPS:TEMP_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD04:SOLPS:TEMP_RB"
    }
   ]
  },
  {
   "title": "COLLECTOR OUTLET TEMP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "target": "LEL:MOD:SCAT:MOD01:CLL:OUTLETTEMP_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD02:CLL:OUTLETTEMP_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD03:CLL:OUTLETTEMP_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD04:CLL:OUTLETTEMP_RB"
    }
   ]
  },
  {
   "title": "COLLECTROR INLET TEMPERATURE ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "target": "LEL:MOD:SCAT:MOD01:CLL:INLETTEMP_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD02:CLL:INLETTEMP_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD03:CLL:INLETTEMP_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD04:CLL:INLETTEMP_RB"
    }
   ]
  },
  {
   "title": "KLYSTRON BODY WATER FLOW",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "target": "LEL:MOD:SCAT:MOD01:KLY:BODYFLOW_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD02:KLY:BODYFLOW_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD03:KLY:BODYFLOW_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD04:KLY:BODYFLOW_RB"
    }
   ]
  },
  {
   "title": "KLYSTRON OUTLET TEMP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "target": "LEL:MOD:SCAT:MOD01:KLY:OUTLETTEMP_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD02:KLY:OUTLETTEMP_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD03:KLY:OUTLETTEMP_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD03:KLY:OUTLETTEMP_RB"
    }
   ]
  },
  {
   "title": "ION PUMP CONTROLLER",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    { "target": "LEL:MOD:SCAT:MOD01:IONPMP:R_RB" },
    { "target": "LEL:MOD:SCAT:MOD02:IONPMP:R_RB" },
    { "target": "LEL:MOD:SCAT:MOD03:IONPMP:R_RB" },
    { "target": "LEL:MOD:SCAT:MOD04:IONPMP:R_RB" }
   ]
  },
  {
   "title": "TRANSFORMER TANK OIL LEVEL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    { "target": "LEL:MOD:SCAT:MOD01:OIL:LVL_RB" },
    { "target": "LEL:MOD:SCAT:MOD02:OIL:LVL_RB" },
    { "target": "LEL:MOD:SCAT:MOD03:OIL:LVL_RB" },
    { "target": "LEL:MOD:SCAT:MOD04:OIL:LVL_RB" }
   ]
  },
  {
   "title": "TRANSFORMER TANK OIL TEMPERATURE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    { "target": "LEL:MOD:SCAT:MOD01:OIL:TEMP_RB" },
    { "target": "LEL:MOD:SCAT:MOD02:OIL:TEMP_RB" },
    { "target": "LEL:MOD:SCAT:MOD03:OIL:TEMP_RB" },
    { "target": "LEL:MOD:SCAT:MOD04:OIL:TEMP_RB" }
   ]
  },
  {
   "title": "SOLENOID 1 TEMPERATURE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "target": "LEL:MOD:SCAT:MOD01:SOLPS:TEMP_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD02:SOLPS:TEMP_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD03:SOLPS:TEMP_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD04:SOLPS:TEMP_RB"
    }
   ]
  },
  {
   "title": "SOLENOID 1 VOLT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "target": "LEL:MOD:SCAT:MOD01:SOLPS:VOLT_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD02:SOLPS:VOLT_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD03:SOLPS:VOLT_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD04:SOLPS:VOLT_RB"
    }
   ]
  },
  {
   "title": "SOLENOID 1 CURRENT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "target": "LEL:MOD:SCAT:MOD01:SOLPS:CURR_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD02:SOLPS:CURR_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD03:SOLPS:CURR_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD04:SOLPS:CURR_RB"
    }
   ]
  },
  {
   "title": "FILAMENT VOLT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "target": "LEL:MOD:SCAT:MOD01:FILPS:VOLT_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD02:FILPS:VOLT_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD03:FILPS:VOLT_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD04:FILPS:VOLT_RB"
    }
   ]
  },
  {
   "title": "FILAMENT CURRENT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "target": "LEL:MOD:SCAT:MOD01:FILPS:CURR_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD02:FILPS:CURR_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD03:FILPS:CURR_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD04:FILPS:CURR_RB"
    }
   ]
  },
  {
   "title": "SET CURRENT READBACK",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "target": "LEL:MOD:SCAT:MOD01:FILPS:CURR_SET_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD02:FILPS:CURR_SET_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD03:FILPS:CURR_SET_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD04:FILPS:CURR_SET_RB"
    }
   ]
  },
  {
   "title": "SET CURRENT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "target": "LEL:MOD:SCAT:MOD01:FILPS:CURR_SP"
    },
    {
     "target": "LEL:MOD:SCAT:MOD02:FILPS:CURR_SP"
    },
    {
     "target": "LEL:MOD:SCAT:MOD03:FILPS:CURR_SP"
    },
    {
     "target": "LEL:MOD:SCAT:MOD04:FILPS:CURR_SP"
    }
   ]
  },
  {
   "title": "PULSE REPETITION RATE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "targets": [
    { "target": "LEL:MOD:SCAT:MOD01:PLS:REPR_RB" },
    { "target": "LEL:MOD:SCAT:MOD02:PLS:REPR_RB" },
    { "target": "LEL:MOD:SCAT:MOD03:PLS:REPR_RB" },
    { "target": "LEL:MOD:SCAT:MOD04:PLS:REPR_RB" }
   ]
  },
  {
   "title": "PULSE VOLT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    { "target": "LEL:MOD:SCAT:MOD01:PLS:VOLT_RB" },
    { "target": "LEL:MOD:SCAT:MOD02:PLS:VOLT_RB" },
    { "target": "LEL:MOD:SCAT:MOD03:PLS:VOLT_RB" },
    { "target": "LEL:MOD:SCAT:MOD04:PLS:VOLT_RB" }
   ]
  },
  {
   "title": "PULSE CURRENT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "targets": [
    { "target": "LEL:MOD:SCAT:MOD01:PLS:CURR_RB" },
    { "target": "LEL:MOD:SCAT:MOD02:PLS:CURR_RB" },
    { "target": "LEL:MOD:SCAT:MOD03:PLS:CURR_RB" },
    { "target": "LEL:MOD:SCAT:MOD04:PLS:CURR_RB" }
   ]
  },
  {
   "title": "PULSE WIDTH READ BACK",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "target": "LEL:MOD:SCAT:MOD01:PLS:WDTH_SET_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD02:PLS:WDTH_SET_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD03:PLS:WDTH_SET_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD04:PLS:WDTH_SET_RB"
    }
   ]
  },
  {
   "title": "PULSE WIDTH",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "targets": [
    { "target": "LEL:MOD:SCAT:MOD01:PLS:WDTH_RB" },
    { "target": "LEL:MOD:SCAT:MOD02:PLS:WDTH_RB" },
    { "target": "LEL:MOD:SCAT:MOD03:PLS:WDTH_RB" },
    { "target": "LEL:MOD:SCAT:MOD04:PLS:WDTH_RB" }
   ]
  },
  {
   "title": "PULSE WIDTH SET POINT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "targets": [
    { "target": "LEL:MOD:SCAT:MOD01:PLS:WDTH_SP" },
    { "target": "LEL:MOD:SCAT:MOD02:PLS:WDTH_SP" },
    { "target": "LEL:MOD:SCAT:MOD03:PLS:WDTH_SP" },
    { "target": "LEL:MOD:SCAT:MOD04:PLS:WDTH_SP" }
   ]
  },
  {
   "title": "CCPS3 VOLT READBACK",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "targets": [
    {
     "target": "LEL:MOD:SCAT:MOD01:CCPS3:VOLT_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD02:CCPS3:VOLT_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD03:CCPS3:VOLT_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD04:CCPS3:VOLT_RB"
    }
   ]
  },
  {
   "title": "CCPS2 VOLT READBACK",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "targets": [
    {
     "target": "LEL:MOD:SCAT:MOD01:CCPS2:VOLT_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD02:CCPS2:VOLT_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD03:CCPS2:VOLT_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD04:CCPS2:VOLT_RB"
    }
   ]
  },
  {
   "title": "CPPS1 VOLT READBACK",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "targets": [
    {
     "target": "LEL:MOD:SCAT:MOD01:CCPS1:VOLT_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD02:CCPS1:VOLT_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD03:CCPS1:VOLT_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD04:CCPS1:VOLT_RB"
    }
   ]
  },
  {
   "title": "SET VOLTAGE READBACK",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "targets": [
    {
     "target": "LEL:MOD:SCAT:MOD01:CCPS:VOLT_SET_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD02:CCPS:VOLT_SET_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD03:CCPS:VOLT_SET_RB"
    },
    {
     "target": "LEL:MOD:SCAT:MOD04:CCPS:VOLT_SET_RB"
    }
   ]
  },
  {
   "title": "SET VOLTAGE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "targets": [
    { "target": "LEL:MOD:SCAT:MOD01:CCPS:V_SP" },
    { "target": "LEL:MOD:SCAT:MOD02:CCPS:V_SP" },
    { "target": "LEL:MOD:SCAT:MOD03:CCPS:V_SP" },
    { "target": "LEL:MOD:SCAT:MOD04:CCPS:V_SP" }
   ]
  }
 ]
}