{
 "title": "Vacuum",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "wgsvpconion04 PRES",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "LEL:VAC:WGC02:VPCON04:IONP13:PRES"
    },
    {
     "target": "LEL:VAC:WGC02:VPCON04:IONP14:PRES"
    },
    {
     "target": "LEL:VAC:WGC02:VPCON04:IONP15:PRES"
    }
   ]
  },
  {
   "title": "wgsvpconion03 PRES",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "target": "LEL:VAC:WGS2:VPCON03:IONP12:PRES"
    },
    {
     "target": "LEL:VAC:WGS2:VPCON03:IONP11:PRES"
    },
    {
     "target": "LEL:VAC:WGS2:VPCON03:IONP10:PRES"
    },
    {
     "target": "LEL:VAC:WGS2:VPCON03:IONP09:PRES"
    }
   ]
  },
  {
   "title": "wgsvpconion02 PRES",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "target": "LEL:VAC:WGS1:VPCON02:IONP05:PRES"
    },
    {
     "target": "LEL:VAC:WGS1:VPCON02:IONP06:PRES"
    },
    {
     "target": "LEL:VAC:WGS1:VPCON02:IONP07:PRES"
    },
    {
     "target": "LEL:VAC:WGS1:VPCON02:IONP08:PRES"
    }
   ]
  },
  {
   "title": "wgsvpconion01 PRES",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "target": "LEL:VAC:WGS1:VPCON01:IONP01:PRES"
    },
    {
     "target": "LEL:VAC:WGS1:VPCON01:IONP02:PRES"
    },
    {
     "target": "LEL:VAC:WGS1:VPCON01:IONP03:PRES"
    },
    {
     "target": "LEL:VAC:WGS1:VPCON01:IONP04:PRES"
    }
   ]
  },
  {
   "title": "vpcon08 PRES",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "target": "LEL:VAC:VPCON08:WGC01IONP02:PRES"
    },
    {
     "target": "LEL:VAC:VPCON08:WGC01IONP03:PRES"
    },
    {
     "target": "LEL:VAC:VPCON08:WGC01IONP04:PRES"
    },
    {
     "target": "LEL:VAC:VPCON08:WGC01IONP05:PRES"
    }
   ]
  },
  {
   "title": "vpcon07 PRES",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "target": "LEL:VAC:VPCON07:WGS03IONP02:PRES"
    },
    {
     "target": "LEL:VAC:VPCON07:WGS03IONP03:PRES"
    },
    {
     "target": "LEL:VAC:VPCON07:WGS03IONP04:PRES"
    },
    {
     "target": "LEL:VAC:VPCON07:WGC01IONP01:PRES"
    }
   ]
  },
  {
   "title": "vpcon06 PRES",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "target": "LEL:VAC:VPCON06:WGS02IONP03:PRES"
    },
    {
     "target": "LEL:VAC:VPCON06:WGS02IONP04:PRES"
    },
    {
     "target": "LEL:VAC:VPCON06:WGS02IONP05:PRES"
    },
    {
     "target": "LEL:VAC:VPCON06:WGS03IONP01:PRES"
    }
   ]
  },
  {
   "title": "vpcon05 PRES",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "target": "LEL:VAC:VPCON05:WGS01IONP05:PRES"
    },
    {
     "target": "LEL:VAC:VPCON05:WGS01IONP06:PRES"
    },
    {
     "target": "LEL:VAC:VPCON05:WGS02IONP02:PRES"
    },
    {
     "target": "LEL:VAC:VPCON05:WGS02IONP01:PRES"
    }
   ]
  },
  {
   "title": "vpcon04 PRES",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "target": "LEL:VAC:VPCON04:WGS01IONP01:PRES"
    },
    {
     "target": "LEL:VAC:VPCON04:WGS01IONP02:PRES"
    },
    {
     "target": "LEL:VAC:VPCON04:WGS01IONP03:PRES"
    },
    {
     "target": "LEL:VAC:VPCON04:WGS01IONP04:PRES"
    }
   ]
  },
  {
   "title": "vgcon02 PRES",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    { "target": "LEL:VAC:VGCON02:CC01:PRES" },
    { "target": "LEL:VAC:VGCON02:CC03:PRES" },
    { "target": "LEL:VAC:VGCON02:CC04:PRES" },
    { "target": "LEL:VAC:VGCON02:CC06:PRES" }
   ]
  },
  {
   "title": "Vacuum",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "targets": [
    { "target": "LEL:VAC:VGCON01:CC08:PRES" },
    { "target": "LEL:VAC:VGCON01:CC09:PRES" }
   ]
  }
 ]
}