# yaml-language-server: $schema=../schemas/ibek.support.schema.json

ioc_name: __IOC_NAME__
description: Sparc cameras

entities:
  - type: ADAravis.aravisCamera
    P: "SPARC:CAM:"
    R: "THV01:"
    PORT: THV01
    ID: Basler-scA640-70gm-21290809
    CLASS: Basler-scA640-70gm
    TIMEOUT: 5

  - type: ADCore.NDPvaPlugin
    PORT: THV01.PVA
    PVNAME: "SPARC:CAM:THV01:PVA:OUTPUT"
    P: "SPARC:CAM:THV01"
    R: ":Pva1:"
    NDARRAY_PORT: THV01
    ENABLED: 1

  - type: ADCore.NDStdArrays
    P: "SPARC:CAM:THV01"
    R: ":image1:"
    PORT: THV01.NTD
    NDARRAY_PORT: THV01
    TYPE: "Int16"
    FTVL: USHORT
    NELEMENTS: 325546
    ENABLED: 1

  - type: ADCore.NDFileTIFF
    PORT: THV01.TIFF
    NDARRAY_PORT: THV01
    P: "SPARC:CAM:THV01:"
    R: "TIFF1:"
    ENABLED: 1

  - type: epics.PostStartupCommand
    command: |
      dbpf("SPARC:CAM:THV01:TIFF1:FilePath", "__DATA_DIR__")
      dbpf("SPARC:CAM:THV01:TIFF1:FileWriteMode",2)
      dbpf("SPARC:CAM:THV01:TIFF1:FileTemplate","%s%s_%3.3d.tiff")

  - type: ADAravis.aravisCamera
    P: "SPARC:CAM:"
    R: "AC101:"
    PORT: AC101
    ID: Basler-scA640-70gm-21273723
    CLASS: Basler-scA640-70gm
    TIMEOUT: 5

  - type: ADCore.NDPvaPlugin
    PORT: AC101.PVA
    PVNAME: "SPARC:CAM:AC101:PVA:OUTPUT"
    P: "SPARC:CAM:AC101"
    R: ":Pva1:"
    NDARRAY_PORT: AC101
    ENABLED: 1

  - type: ADCore.NDStdArrays
    P: "SPARC:CAM:AC101"
    R: ":image1:"
    PORT: AC101.NTD
    NDARRAY_PORT: AC101
    TYPE: "Int16"
    FTVL: USHORT
    NELEMENTS: 325546
    ENABLED: 1

  - type: ADCore.NDFileTIFF
    PORT: AC101.TIFF
    NDARRAY_PORT: AC101
    P: "SPARC:CAM:AC101:"
    R: "TIFF1:"
    ENABLED: 1

  - type: epics.PostStartupCommand
    command: |
      dbpf("SPARC:CAM:AC101:TIFF1:FilePath", "__DATA_DIR__")
      dbpf("SPARC:CAM:AC101:TIFF1:FileWriteMode",2)
      dbpf("SPARC:CAM:AC101:TIFF1:FileTemplate","%s%s_%3.3d.tiff")

  
  - type: ADAravis.aravisCamera
    P: "SPARC:CAM:"
    R: "UTL01:"
    PORT: UTL01
    ID: Basler-scA640-70gm-21732890
    CLASS: Basler-scA640-70gm
    TIMEOUT: 5

  - type: ADCore.NDPvaPlugin
    PORT: UTL01.PVA
    PVNAME: "SPARC:CAM:UTL01:PVA:OUTPUT"
    P: "SPARC:CAM:UTL01"
    R: ":Pva1:"
    NDARRAY_PORT: UTL01
    ENABLED: 1

  - type: ADCore.NDStdArrays
    P: "SPARC:CAM:UTL01"
    R: ":image1:"
    PORT: UTL01.NTD
    NDARRAY_PORT: UTL01
    TYPE: "Int16"
    FTVL: USHORT
    NELEMENTS: 325546
    ENABLED: 1

  - type: ADCore.NDFileTIFF
    PORT: UTL01.TIFF
    NDARRAY_PORT: UTL01
    P: "SPARC:CAM:UTL01:"
    R: "TIFF1:"
    ENABLED: 1

  - type: epics.PostStartupCommand
    command: |
      dbpf("SPARC:CAM:UTL01:TIFF1:FilePath", "__DATA_DIR__")
      dbpf("SPARC:CAM:UTL01:TIFF1:FileWriteMode",2)
      dbpf("SPARC:CAM:UTL01:TIFF1:FileTemplate","%s%s_%3.3d.tiff")

  - type: ADAravis.aravisCamera
    P: "SPARC:CAM:"
    R: "PLV02:"
    PORT: PLV02
    ID: Basler-scA640-70gm-21732894
    CLASS: Basler-scA640-70gm
    TIMEOUT: 5

  - type: ADCore.NDPvaPlugin
    PORT: PLV02.PVA
    PVNAME: "SPARC:CAM:PLV02:PVA:OUTPUT"
    P: "SPARC:CAM:PLV02"
    R: ":Pva1:"
    NDARRAY_PORT: PLV02
    ENABLED: 1

  - type: ADCore.NDStdArrays
    P: "SPARC:CAM:PLV02"
    R: ":image1:"
    PORT: PLV02.NTD
    NDARRAY_PORT: PLV02
    TYPE: "Int16"
    FTVL: USHORT
    NELEMENTS: 325546
    ENABLED: 1

  - type: ADCore.NDFileTIFF
    PORT: PLV02.TIFF
    NDARRAY_PORT: PLV02
    P: "SPARC:CAM:PLV02:"
    R: "TIFF1:"
    ENABLED: 1

  - type: epics.PostStartupCommand
    command: |
      dbpf("SPARC:CAM:PLV02:TIFF1:FilePath", "__DATA_DIR__")
      dbpf("SPARC:CAM:PLV02:TIFF1:FileWriteMode",2)
      dbpf("SPARC:CAM:PLV02:TIFF1:FileTemplate","%s%s_%3.3d.tiff")

  - type: ADAravis.aravisCamera
    P: "SPARC:CAM:"
    R: "AC201:"
    PORT: AC201
    ID: Basler-scA640-70gm-21732900
    CLASS: Basler-scA640-70gm
    TIMEOUT: 5

  - type: ADCore.NDPvaPlugin
    PORT: AC201.PVA
    PVNAME: "SPARC:CAM:AC201:PVA:OUTPUT"
    P: "SPARC:CAM:AC201"
    R: ":Pva1:"
    NDARRAY_PORT: AC201
    ENABLED: 1

  - type: ADCore.NDStdArrays
    P: "SPARC:CAM:AC201"
    R: ":image1:"
    PORT: AC201.NTD
    NDARRAY_PORT: AC201
    TYPE: "Int16"
    FTVL: USHORT
    NELEMENTS: 325546
    ENABLED: 1

  - type: ADCore.NDFileTIFF
    PORT: AC201.TIFF
    NDARRAY_PORT: AC201
    P: "SPARC:CAM:AC201:"
    R: "TIFF1:"
    ENABLED: 1

  - type: epics.PostStartupCommand
    command: |
      dbpf("SPARC:CAM:AC201:TIFF1:FilePath", "__DATA_DIR__")
      dbpf("SPARC:CAM:AC201:TIFF1:FileWriteMode",2)
      dbpf("SPARC:CAM:AC201:TIFF1:FileTemplate","%s%s_%3.3d.tiff")

  - type: ADAravis.aravisCamera
    P: "SPARC:CAM:"
    R: "DGL00:"
    PORT: DGL00
    ID: Basler-scA640-70gm-23665716
    CLASS: Basler-scA640-70gm
    TIMEOUT: 5

  - type: ADCore.NDPvaPlugin
    PORT: DGL00.PVA
    PVNAME: "SPARC:CAM:DGL00:PVA:OUTPUT"
    P: "SPARC:CAM:DGL00"
    R: ":Pva1:"
    NDARRAY_PORT: DGL00
    ENABLED: 1

  - type: ADCore.NDStdArrays
    P: "SPARC:CAM:DGL00"
    R: ":image1:"
    PORT: DGL00.NTD
    NDARRAY_PORT: DGL00
    TYPE: "Int16"
    FTVL: USHORT
    NELEMENTS: 325546
    ENABLED: 1

  - type: ADCore.NDFileTIFF
    PORT: DGL00.TIFF
    NDARRAY_PORT: DGL00
    P: "SPARC:CAM:DGL00:"
    R: "TIFF1:"
    ENABLED: 1

  - type: epics.PostStartupCommand
    command: |
      dbpf("SPARC:CAM:DGL00:TIFF1:FilePath", "__DATA_DIR__")
      dbpf("SPARC:CAM:DGL00:TIFF1:FileWriteMode",2)
      dbpf("SPARC:CAM:DGL00:TIFF1:FileTemplate","%s%s_%3.3d.tiff")

  - type: ADAravis.aravisCamera
    P: "SPARC:CAM:"
    R: "DGL01:"
    PORT: DGL01
    ID: Basler-scA640-70gm-21732893
    CLASS: Basler-scA640-70gm
    TIMEOUT: 5

  - type: ADCore.NDPvaPlugin
    PORT: DGL01.PVA
    PVNAME: "SPARC:CAM:DGL01:PVA:OUTPUT"
    P: "SPARC:CAM:DGL01"
    R: ":Pva1:"
    NDARRAY_PORT: DGL01
    ENABLED: 1

  - type: ADCore.NDStdArrays
    P: "SPARC:CAM:DGL01"
    R: ":image1:"
    PORT: DGL01.NTD
    NDARRAY_PORT: DGL01
    TYPE: "Int16"
    FTVL: USHORT
    NELEMENTS: 325546
    ENABLED: 1

  - type: ADCore.NDFileTIFF
    PORT: DGL01.TIFF
    NDARRAY_PORT: DGL01
    P: "SPARC:CAM:DGL01:"
    R: "TIFF1:"
    ENABLED: 1

  - type: epics.PostStartupCommand
    command: |
      dbpf("SPARC:CAM:DGL01:TIFF1:FilePath", "__DATA_DIR__")
      dbpf("SPARC:CAM:DGL01:TIFF1:FileWriteMode",2)
      dbpf("SPARC:CAM:DGL01:TIFF1:FileTemplate","%s%s_%3.3d.tiff")

  - type: ADAravis.aravisCamera
    P: "SPARC:CAM:"
    R: "GUN01:"
    PORT: GUN01
    ID: Basler-scA640-70gm-23665718
    CLASS: Basler-scA640-70gm
    TIMEOUT: 5

  - type: ADCore.NDPvaPlugin
    PORT: GUN01.PVA
    PVNAME: "SPARC:CAM:GUN01:PVA:OUTPUT"
    P: "SPARC:CAM:GUN01"
    R: ":Pva1:"
    NDARRAY_PORT: GUN01
    ENABLED: 1

  - type: ADCore.NDStdArrays
    P: "SPARC:CAM:GUN01"
    R: ":image1:"
    PORT: GUN01.NTD
    NDARRAY_PORT: GUN01
    TYPE: "Int16"
    FTVL: USHORT
    NELEMENTS: 325546
    ENABLED: 1

  - type: ADCore.NDFileTIFF
    PORT: GUN01.TIFF
    NDARRAY_PORT: GUN01
    P: "SPARC:CAM:GUN01:"
    R: "TIFF1:"
    ENABLED: 1

  - type: epics.PostStartupCommand
    command: |
      dbpf("SPARC:CAM:GUN01:TIFF1:FilePath", "__DATA_DIR__")
      dbpf("SPARC:CAM:GUN01:TIFF1:FileWriteMode",2)
      dbpf("SPARC:CAM:GUN01:TIFF1:FileTemplate","%s%s_%3.3d.tiff")

  - type: ADAravis.aravisCamera
    P: "SPARC:CAM:"
    R: "PLV01:"
    PORT: PLV01
    ID: Basler-scA640-74gm-21002010
    CLASS: Basler-scA640-70gm
    TIMEOUT: 5

  - type: ADCore.NDPvaPlugin
    PORT: PLV01.PVA
    PVNAME: "SPARC:CAM:PLV01:PVA:OUTPUT"
    P: "SPARC:CAM:PLV01"
    R: ":Pva1:"
    NDARRAY_PORT: PLV01
    ENABLED: 1

  - type: ADCore.NDStdArrays
    P: "SPARC:CAM:PLV01"
    R: ":image1:"
    PORT: PLV01.NTD
    NDARRAY_PORT: PLV01
    TYPE: "Int16"
    FTVL: USHORT
    NELEMENTS: 325546
    ENABLED: 1

  - type: ADCore.NDFileTIFF
    PORT: PLV01.TIFF
    NDARRAY_PORT: PLV01
    P: "SPARC:CAM:PLV01:"
    R: "TIFF1:"
    ENABLED: 1

  - type: epics.PostStartupCommand
    command: |
      dbpf("SPARC:CAM:PLV01:TIFF1:FilePath", "__DATA_DIR__")
      dbpf("SPARC:CAM:PLV01:TIFF1:FileWriteMode",2)
      dbpf("SPARC:CAM:PLV01:TIFF1:FileTemplate","%s%s_%3.3d.tiff")

  - type: ADAravis.aravisCamera
    P: "SPARC:CAM:"
    R: "UTL02:"
    PORT: UTL02
    ID: Basler-scA640-74gm-21290828
    CLASS: Basler-scA640-70gm
    TIMEOUT: 5

  - type: ADCore.NDPvaPlugin
    PORT: UTL02.PVA
    PVNAME: "SPARC:CAM:UTL02:PVA:OUTPUT"
    P: "SPARC:CAM:UTL02"
    R: ":Pva1:"
    NDARRAY_PORT: UTL02
    ENABLED: 1

  - type: ADCore.NDStdArrays
    P: "SPARC:CAM:UTL02"
    R: ":image1:"
    PORT: UTL02.NTD
    NDARRAY_PORT: UTL02
    TYPE: "Int16"
    FTVL: USHORT
    NELEMENTS: 325546
    ENABLED: 1

  - type: ADCore.NDFileTIFF
    PORT: UTL02.TIFF
    NDARRAY_PORT: UTL02
    P: "SPARC:CAM:UTL02:"
    R: "TIFF1:"
    ENABLED: 1

  - type: epics.PostStartupCommand
    command: |
      dbpf("SPARC:CAM:UTL02:TIFF1:FilePath", "__DATA_DIR__")
      dbpf("SPARC:CAM:UTL02:TIFF1:FileWriteMode",2)
      dbpf("SPARC:CAM:UTL02:TIFF1:FileTemplate","%s%s_%3.3d.tiff")

  - type: ADAravis.aravisCamera
    P: "SPARC:CAM:"
    R: "EOS02:"
    PORT: EOS02
    ID: Basler-scA640-74gm-21290841
    CLASS: Basler-scA640-70gm
    TIMEOUT: 5

  - type: ADCore.NDPvaPlugin
    PORT: EOS02.PVA
    PVNAME: "SPARC:CAM:EOS02:PVA:OUTPUT"
    P: "SPARC:CAM:EOS02"
    R: ":Pva1:"
    NDARRAY_PORT: EOS02
    ENABLED: 1

  - type: ADCore.NDStdArrays
    P: "SPARC:CAM:EOS02"
    R: ":image1:"
    PORT: EOS02.NTD
    NDARRAY_PORT: EOS02
    TYPE: "Int16"
    FTVL: USHORT
    NELEMENTS: 325546
    ENABLED: 1

  - type: ADCore.NDFileTIFF
    PORT: EOS02.TIFF
    NDARRAY_PORT: EOS02
    P: "SPARC:CAM:EOS02:"
    R: "TIFF1:"
    ENABLED: 1

  - type: epics.PostStartupCommand
    command: |
      dbpf("SPARC:CAM:EOS02:TIFF1:FilePath", "__DATA_DIR__")
      dbpf("SPARC:CAM:EOS02:TIFF1:FileWriteMode",2)
      dbpf("SPARC:CAM:EOS02:TIFF1:FileTemplate","%s%s_%3.3d.tiff")

  - type: ADAravis.aravisCamera
    P: "SPARC:CAM:"
    R: "EOS01:"
    PORT: EOS01
    ID: Basler-scA640-74gm-21751350
    CLASS: Basler-scA640-70gm
    TIMEOUT: 5

  - type: ADCore.NDPvaPlugin
    PORT: EOS01.PVA
    PVNAME: "SPARC:CAM:EOS01:PVA:OUTPUT"
    P: "SPARC:CAM:EOS01"
    R: ":Pva1:"
    NDARRAY_PORT: EOS01
    ENABLED: 1

  - type: ADCore.NDStdArrays
    P: "SPARC:CAM:EOS01"
    R: ":image1:"
    PORT: EOS01.NTD
    NDARRAY_PORT: EOS01
    TYPE: "Int16"
    FTVL: USHORT
    NELEMENTS: 325546
    ENABLED: 1

  - type: ADCore.NDFileTIFF
    PORT: EOS01.TIFF
    NDARRAY_PORT: EOS01
    P: "SPARC:CAM:EOS01:"
    R: "TIFF1:"
    ENABLED: 1

  - type: epics.PostStartupCommand
    command: |
      dbpf("SPARC:CAM:EOS01:TIFF1:FilePath", "__DATA_DIR__")
      dbpf("SPARC:CAM:EOS01:TIFF1:FileWriteMode",2)
      dbpf("SPARC:CAM:EOS01:TIFF1:FileTemplate","%s%s_%3.3d.tiff")

  - type: ADAravis.aravisCamera
    P: "SPARC:CAM:"
    R: "AC301:"
    PORT: AC301
    ID: Basler-scA640-74gm-21751352
    CLASS: Basler-scA640-70gm
    TIMEOUT: 5

  - type: ADCore.NDPvaPlugin
    PORT: AC301.PVA
    PVNAME: "SPARC:CAM:AC301:PVA:OUTPUT"
    P: "SPARC:CAM:AC301"
    R: ":Pva1:"
    NDARRAY_PORT: AC301
    ENABLED: 1

  - type: ADCore.NDStdArrays
    P: "SPARC:CAM:AC301"
    R: ":image1:"
    PORT: AC301.NTD
    NDARRAY_PORT: AC301
    TYPE: "Int16"
    FTVL: USHORT
    NELEMENTS: 325546
    ENABLED: 1

  - type: ADCore.NDFileTIFF
    PORT: AC301.TIFF
    NDARRAY_PORT: AC301
    P: "SPARC:CAM:AC301:"
    R: "TIFF1:"
    ENABLED: 1

  - type: epics.PostStartupCommand
    command: |
      dbpf("SPARC:CAM:AC301:TIFF1:FilePath", "__DATA_DIR__")
      dbpf("SPARC:CAM:AC301:TIFF1:FileWriteMode",2)
      dbpf("SPARC:CAM:AC301:TIFF1:FileTemplate","%s%s_%3.3d.tiff")
      dbl("*") > __CONFIG_DIR__/pvlist.txt           ## dumps PV NAMES


