# yaml-language-server: $schema=../schemas/ibek.support.schema.json

ioc_name: __IOC_NAME__
description: Sparc cameras

entities:
  - type: ADAravis.aravisCamera
    P: "SPARC:CAM:"
    R: "TestEpics:"
    PORT: TestEpics
    ID: Basler-a2A1920-51gcBAS-40204275
    CLASS: Basler-a2A2600-20gmBAS

  - type: ADCore.NDPvaPlugin
    PORT: TestEpics.PVA
    PVNAME: "SPARC:CAM:TestEpics:PVA:OUTPUT"
    P: "SPARC:CAM:TestEpics"
    R: ":Pva1:"
    NDARRAY_PORT: TestEpics
    ENABLED: 1

  - type: ADCore.NDStdArrays
    P: "SPARC:CAM:TestEpics"
    R: ":image1:"
    PORT: TestEpics.NTD
    NDARRAY_PORT: TestEpics
    TYPE: "Int16"
    FTVL: USHORT
    NELEMENTS: 325546
    ENABLED: 1

  - type: ADCore.NDFileTIFF
    PORT: TestEpics.TIFF
    NDARRAY_PORT: TestEpics
    P: "SPARC:CAM:TestEpics:"
    R: "TIFF1:"
    ENABLED: 1

  - type: epics.PostStartupCommand
    command: |
      dbpf("SPARC:CAM:TestEpics:TIFF1:FilePath", "__DATA_DIR__")
      dbpf("SPARC:CAM:TestEpics:TIFF1:FileWriteMode",2)
      dbpf("SPARC:CAM:TestEpics:TIFF1:FileTemplate","%s%s_%3.3d.tiff")

  - type: ADAravis.aravisCamera
    P: "SPARC:CAM:"
    R: "AC1CAMO1:"
    PORT: AC1CAMO1
    ID: Basler-scA640-70gm-21273723
    CLASS: Basler-scA640-70gm

  - type: ADCore.NDPvaPlugin
    PORT: AC1CAMO1.PVA
    PVNAME: "SPARC:CAM:AC1CAMO1:PVA:OUTPUT"
    P: "SPARC:CAM:AC1CAMO1"
    R: ":Pva1:"
    NDARRAY_PORT: AC1CAMO1
    ENABLED: 1

  - type: ADCore.NDStdArrays
    P: "SPARC:CAM:AC1CAMO1"
    R: ":image1:"
    PORT: AC1CAMO1.NTD
    NDARRAY_PORT: AC1CAMO1
    TYPE: "Int16"
    FTVL: USHORT
    NELEMENTS: 325546
    ENABLED: 1

  - type: ADCore.NDFileTIFF
    PORT: AC1CAMO1.TIFF
    NDARRAY_PORT: AC1CAMO1
    P: "SPARC:CAM:AC1CAMO1:"
    R: "TIFF1:"
    ENABLED: 1

  - type: epics.PostStartupCommand
    command: |
      dbpf("SPARC:CAM:AC1CAMO1:TIFF1:FilePath", "__DATA_DIR__")
      dbpf("SPARC:CAM:AC1CAMO1:TIFF1:FileWriteMode",2)
      dbpf("SPARC:CAM:AC1CAMO1:TIFF1:FileTemplate","%s%s_%3.3d.tiff")

  - type: ADAravis.aravisCamera
    P: "SPARC:CAM:"
    R: "THVCAMO1:"
    PORT: THVCAMO1
    ID: Basler-scA640-70gm-21290809
    CLASS: Basler-scA640-70gm

  - type: ADCore.NDPvaPlugin
    PORT: THVCAMO1.PVA
    PVNAME: "SPARC:CAM:THVCAMO1:PVA:OUTPUT"
    P: "SPARC:CAM:THVCAMO1"
    R: ":Pva1:"
    NDARRAY_PORT: THVCAMO1
    ENABLED: 1

  - type: ADCore.NDStdArrays
    P: "SPARC:CAM:THVCAMO1"
    R: ":image1:"
    PORT: THVCAMO1.NTD
    NDARRAY_PORT: THVCAMO1
    TYPE: "Int16"
    FTVL: USHORT
    NELEMENTS: 325546
    ENABLED: 1

  - type: ADCore.NDFileTIFF
    PORT: THVCAMO1.TIFF
    NDARRAY_PORT: THVCAMO1
    P: "SPARC:CAM:THVCAMO1:"
    R: "TIFF1:"
    ENABLED: 1

  - type: epics.PostStartupCommand
    command: |
      dbpf("SPARC:CAM:THVCAMO1:TIFF1:FilePath", "__DATA_DIR__")
      dbpf("SPARC:CAM:THVCAMO1:TIFF1:FileWriteMode",2)
      dbpf("SPARC:CAM:THVCAMO1:TIFF1:FileTemplate","%s%s_%3.3d.tiff")

  - type: ADAravis.aravisCamera
    P: "SPARC:CAM:"
    R: "UTLCAMO1:"
    PORT: UTLCAMO1
    ID: Basler-scA640-70gm-21732890
    CLASS: Basler-scA640-70gm

  - type: ADCore.NDPvaPlugin
    PORT: UTLCAMO1.PVA
    PVNAME: "SPARC:CAM:UTLCAMO1:PVA:OUTPUT"
    P: "SPARC:CAM:UTLCAMO1"
    R: ":Pva1:"
    NDARRAY_PORT: UTLCAMO1
    ENABLED: 1

  - type: ADCore.NDStdArrays
    P: "SPARC:CAM:UTLCAMO1"
    R: ":image1:"
    PORT: UTLCAMO1.NTD
    NDARRAY_PORT: UTLCAMO1
    TYPE: "Int16"
    FTVL: USHORT
    NELEMENTS: 325546
    ENABLED: 1

  - type: ADCore.NDFileTIFF
    PORT: UTLCAMO1.TIFF
    NDARRAY_PORT: UTLCAMO1
    P: "SPARC:CAM:UTLCAMO1:"
    R: "TIFF1:"
    ENABLED: 1

  - type: epics.PostStartupCommand
    command: |
      dbpf("SPARC:CAM:UTLCAMO1:TIFF1:FilePath", "__DATA_DIR__")
      dbpf("SPARC:CAM:UTLCAMO1:TIFF1:FileWriteMode",2)
      dbpf("SPARC:CAM:UTLCAMO1:TIFF1:FileTemplate","%s%s_%3.3d.tiff")

  - type: ADAravis.aravisCamera
    P: "SPARC:CAM:"
    R: "PLVCAMO2:"
    PORT: PLVCAMO2
    ID: Basler-scA640-70gm-21732894
    CLASS: Basler-scA640-70gm

  - type: ADCore.NDPvaPlugin
    PORT: PLVCAMO2.PVA
    PVNAME: "SPARC:CAM:PLVCAMO2:PVA:OUTPUT"
    P: "SPARC:CAM:PLVCAMO2"
    R: ":Pva1:"
    NDARRAY_PORT: PLVCAMO2
    ENABLED: 1

  - type: ADCore.NDStdArrays
    P: "SPARC:CAM:PLVCAMO2"
    R: ":image1:"
    PORT: PLVCAMO2.NTD
    NDARRAY_PORT: PLVCAMO2
    TYPE: "Int16"
    FTVL: USHORT
    NELEMENTS: 325546
    ENABLED: 1

  - type: ADCore.NDFileTIFF
    PORT: PLVCAMO2.TIFF
    NDARRAY_PORT: PLVCAMO2
    P: "SPARC:CAM:PLVCAMO2:"
    R: "TIFF1:"
    ENABLED: 1

  - type: epics.PostStartupCommand
    command: |
      dbpf("SPARC:CAM:PLVCAMO2:TIFF1:FilePath", "__DATA_DIR__")
      dbpf("SPARC:CAM:PLVCAMO2:TIFF1:FileWriteMode",2)
      dbpf("SPARC:CAM:PLVCAMO2:TIFF1:FileTemplate","%s%s_%3.3d.tiff")

  - type: ADAravis.aravisCamera
    P: "SPARC:CAM:"
    R: "AC2CAM01:"
    PORT: AC2CAM01
    ID: Basler-scA640-70gm-21732900
    CLASS: Basler-scA640-70gm

  - type: ADCore.NDPvaPlugin
    PORT: AC2CAM01.PVA
    PVNAME: "SPARC:CAM:AC2CAM01:PVA:OUTPUT"
    P: "SPARC:CAM:AC2CAM01"
    R: ":Pva1:"
    NDARRAY_PORT: AC2CAM01
    ENABLED: 1

  - type: ADCore.NDStdArrays
    P: "SPARC:CAM:AC2CAM01"
    R: ":image1:"
    PORT: AC2CAM01.NTD
    NDARRAY_PORT: AC2CAM01
    TYPE: "Int16"
    FTVL: USHORT
    NELEMENTS: 325546
    ENABLED: 1

  - type: ADCore.NDFileTIFF
    PORT: AC2CAM01.TIFF
    NDARRAY_PORT: AC2CAM01
    P: "SPARC:CAM:AC2CAM01:"
    R: "TIFF1:"
    ENABLED: 1

  - type: epics.PostStartupCommand
    command: |
      dbpf("SPARC:CAM:AC2CAM01:TIFF1:FilePath", "__DATA_DIR__")
      dbpf("SPARC:CAM:AC2CAM01:TIFF1:FileWriteMode",2)
      dbpf("SPARC:CAM:AC2CAM01:TIFF1:FileTemplate","%s%s_%3.3d.tiff")

  - type: ADAravis.aravisCamera
    P: "SPARC:CAM:"
    R: "DGLCAMO0:"
    PORT: DGLCAMO0
    ID: Basler-scA640-70gm-23665716
    CLASS: Basler-scA640-70gm

  - type: ADCore.NDPvaPlugin
    PORT: DGLCAMO0.PVA
    PVNAME: "SPARC:CAM:DGLCAMO0:PVA:OUTPUT"
    P: "SPARC:CAM:DGLCAMO0"
    R: ":Pva1:"
    NDARRAY_PORT: DGLCAMO0
    ENABLED: 1

  - type: ADCore.NDStdArrays
    P: "SPARC:CAM:DGLCAMO0"
    R: ":image1:"
    PORT: DGLCAMO0.NTD
    NDARRAY_PORT: DGLCAMO0
    TYPE: "Int16"
    FTVL: USHORT
    NELEMENTS: 325546
    ENABLED: 1

  - type: ADCore.NDFileTIFF
    PORT: DGLCAMO0.TIFF
    NDARRAY_PORT: DGLCAMO0
    P: "SPARC:CAM:DGLCAMO0:"
    R: "TIFF1:"
    ENABLED: 1

  - type: epics.PostStartupCommand
    command: |
      dbpf("SPARC:CAM:DGLCAMO0:TIFF1:FilePath", "__DATA_DIR__")
      dbpf("SPARC:CAM:DGLCAMO0:TIFF1:FileWriteMode",2)
      dbpf("SPARC:CAM:DGLCAMO0:TIFF1:FileTemplate","%s%s_%3.3d.tiff")

  - type: ADAravis.aravisCamera
    P: "SPARC:CAM:"
    R: "GUNCAMO1:"
    PORT: GUNCAMO1
    ID: Basler-scA640-70gm-23665718
    CLASS: Basler-scA640-70gm

  - type: ADCore.NDPvaPlugin
    PORT: GUNCAMO1.PVA
    PVNAME: "SPARC:CAM:GUNCAMO1:PVA:OUTPUT"
    P: "SPARC:CAM:GUNCAMO1"
    R: ":Pva1:"
    NDARRAY_PORT: GUNCAMO1
    ENABLED: 1

  - type: ADCore.NDStdArrays
    P: "SPARC:CAM:GUNCAMO1"
    R: ":image1:"
    PORT: GUNCAMO1.NTD
    NDARRAY_PORT: GUNCAMO1
    TYPE: "Int16"
    FTVL: USHORT
    NELEMENTS: 325546
    ENABLED: 1

  - type: ADCore.NDFileTIFF
    PORT: GUNCAMO1.TIFF
    NDARRAY_PORT: GUNCAMO1
    P: "SPARC:CAM:GUNCAMO1:"
    R: "TIFF1:"
    ENABLED: 1

  - type: epics.PostStartupCommand
    command: |
      dbpf("SPARC:CAM:GUNCAMO1:TIFF1:FilePath", "__DATA_DIR__")
      dbpf("SPARC:CAM:GUNCAMO1:TIFF1:FileWriteMode",2)
      dbpf("SPARC:CAM:GUNCAMO1:TIFF1:FileTemplate","%s%s_%3.3d.tiff")

  - type: ADAravis.aravisCamera
    P: "SPARC:CAM:"
    R: "PLVCAMO1:"
    PORT: PLVCAMO1
    ID: Basler-scA640-74gm-21002010
    CLASS: Basler-scA640-70gm

  - type: ADCore.NDPvaPlugin
    PORT: PLVCAMO1.PVA
    PVNAME: "SPARC:CAM:PLVCAMO1:PVA:OUTPUT"
    P: "SPARC:CAM:PLVCAMO1"
    R: ":Pva1:"
    NDARRAY_PORT: PLVCAMO1
    ENABLED: 1

  - type: ADCore.NDStdArrays
    P: "SPARC:CAM:PLVCAMO1"
    R: ":image1:"
    PORT: PLVCAMO1.NTD
    NDARRAY_PORT: PLVCAMO1
    TYPE: "Int16"
    FTVL: USHORT
    NELEMENTS: 325546
    ENABLED: 1

  - type: ADCore.NDFileTIFF
    PORT: PLVCAMO1.TIFF
    NDARRAY_PORT: PLVCAMO1
    P: "SPARC:CAM:PLVCAMO1:"
    R: "TIFF1:"
    ENABLED: 1

  - type: epics.PostStartupCommand
    command: |
      dbpf("SPARC:CAM:PLVCAMO1:TIFF1:FilePath", "__DATA_DIR__")
      dbpf("SPARC:CAM:PLVCAMO1:TIFF1:FileWriteMode",2)
      dbpf("SPARC:CAM:PLVCAMO1:TIFF1:FileTemplate","%s%s_%3.3d.tiff")

  - type: ADAravis.aravisCamera
    P: "SPARC:CAM:"
    R: "UTLCAMO2:"
    PORT: UTLCAMO2
    ID: Basler-scA640-74gm-21290828
    CLASS: Basler-scA640-70gm

  - type: ADCore.NDPvaPlugin
    PORT: UTLCAMO2.PVA
    PVNAME: "SPARC:CAM:UTLCAMO2:PVA:OUTPUT"
    P: "SPARC:CAM:UTLCAMO2"
    R: ":Pva1:"
    NDARRAY_PORT: UTLCAMO2
    ENABLED: 1

  - type: ADCore.NDStdArrays
    P: "SPARC:CAM:UTLCAMO2"
    R: ":image1:"
    PORT: UTLCAMO2.NTD
    NDARRAY_PORT: UTLCAMO2
    TYPE: "Int16"
    FTVL: USHORT
    NELEMENTS: 325546
    ENABLED: 1

  - type: ADCore.NDFileTIFF
    PORT: UTLCAMO2.TIFF
    NDARRAY_PORT: UTLCAMO2
    P: "SPARC:CAM:UTLCAMO2:"
    R: "TIFF1:"
    ENABLED: 1

  - type: epics.PostStartupCommand
    command: |
      dbpf("SPARC:CAM:UTLCAMO2:TIFF1:FilePath", "__DATA_DIR__")
      dbpf("SPARC:CAM:UTLCAMO2:TIFF1:FileWriteMode",2)
      dbpf("SPARC:CAM:UTLCAMO2:TIFF1:FileTemplate","%s%s_%3.3d.tiff")

  - type: ADAravis.aravisCamera
    P: "SPARC:CAM:"
    R: "OSCAMO2:"
    PORT: OSCAMO2
    ID: Basler-scA640-74gm-21290841
    CLASS: Basler-scA640-70gm

  - type: ADCore.NDPvaPlugin
    PORT: OSCAMO2.PVA
    PVNAME: "SPARC:CAM:OSCAMO2:PVA:OUTPUT"
    P: "SPARC:CAM:OSCAMO2"
    R: ":Pva1:"
    NDARRAY_PORT: OSCAMO2
    ENABLED: 1

  - type: ADCore.NDStdArrays
    P: "SPARC:CAM:OSCAMO2"
    R: ":image1:"
    PORT: OSCAMO2.NTD
    NDARRAY_PORT: OSCAMO2
    TYPE: "Int16"
    FTVL: USHORT
    NELEMENTS: 325546
    ENABLED: 1

  - type: ADCore.NDFileTIFF
    PORT: OSCAMO2.TIFF
    NDARRAY_PORT: OSCAMO2
    P: "SPARC:CAM:OSCAMO2:"
    R: "TIFF1:"
    ENABLED: 1

  - type: epics.PostStartupCommand
    command: |
      dbpf("SPARC:CAM:OSCAMO2:TIFF1:FilePath", "__DATA_DIR__")
      dbpf("SPARC:CAM:OSCAMO2:TIFF1:FileWriteMode",2)
      dbpf("SPARC:CAM:OSCAMO2:TIFF1:FileTemplate","%s%s_%3.3d.tiff")

  - type: ADAravis.aravisCamera
    P: "SPARC:CAM:"
    R: "OSCAMO1:"
    PORT: OSCAMO1
    ID: Basler-scA640-74gm-21751350
    CLASS: Basler-scA640-70gm

  - type: ADCore.NDPvaPlugin
    PORT: OSCAMO1.PVA
    PVNAME: "SPARC:CAM:OSCAMO1:PVA:OUTPUT"
    P: "SPARC:CAM:OSCAMO1"
    R: ":Pva1:"
    NDARRAY_PORT: OSCAMO1
    ENABLED: 1

  - type: ADCore.NDStdArrays
    P: "SPARC:CAM:OSCAMO1"
    R: ":image1:"
    PORT: OSCAMO1.NTD
    NDARRAY_PORT: OSCAMO1
    TYPE: "Int16"
    FTVL: USHORT
    NELEMENTS: 325546
    ENABLED: 1

  - type: ADCore.NDFileTIFF
    PORT: OSCAMO1.TIFF
    NDARRAY_PORT: OSCAMO1
    P: "SPARC:CAM:OSCAMO1:"
    R: "TIFF1:"
    ENABLED: 1

  - type: epics.PostStartupCommand
    command: |
      dbpf("SPARC:CAM:OSCAMO1:TIFF1:FilePath", "__DATA_DIR__")
      dbpf("SPARC:CAM:OSCAMO1:TIFF1:FileWriteMode",2)
      dbpf("SPARC:CAM:OSCAMO1:TIFF1:FileTemplate","%s%s_%3.3d.tiff")

  - type: ADAravis.aravisCamera
    P: "SPARC:CAM:"
    R: "AC3CAM01:"
    PORT: AC3CAM01
    ID: Basler-scA640-74gm-21751352
    CLASS: Basler-scA640-70gm

  - type: ADCore.NDPvaPlugin
    PORT: AC3CAM01.PVA
    PVNAME: "SPARC:CAM:AC3CAM01:PVA:OUTPUT"
    P: "SPARC:CAM:AC3CAM01"
    R: ":Pva1:"
    NDARRAY_PORT: AC3CAM01
    ENABLED: 1

  - type: ADCore.NDStdArrays
    P: "SPARC:CAM:AC3CAM01"
    R: ":image1:"
    PORT: AC3CAM01.NTD
    NDARRAY_PORT: AC3CAM01
    TYPE: "Int16"
    FTVL: USHORT
    NELEMENTS: 325546
    ENABLED: 1

  - type: ADCore.NDFileTIFF
    PORT: AC3CAM01.TIFF
    NDARRAY_PORT: AC3CAM01
    P: "SPARC:CAM:AC3CAM01:"
    R: "TIFF1:"
    ENABLED: 1

  - type: epics.PostStartupCommand
    command: |
      dbl  > __CONFIG_DIR__/pvlist.txt           ## dumps PV NAMES
      dbpf("SPARC:CAM:AC3CAM01:TIFF1:FilePath", "__DATA_DIR__")
      dbpf("SPARC:CAM:AC3CAM01:TIFF1:FileWriteMode",2)
      dbpf("SPARC:CAM:AC3CAM01:TIFF1:FileTemplate","%s%s_%3.3d.tiff")

