# yaml-language-server: $schema=../schemas/ibek.support.schema.json

ioc_name: __IOC_NAME__
description: Sparc cameras

entities:
  - type: ADAravis.aravisCamera
    P: "SPARC:CAM:"
    R: "TestEpics:"
    PORT: TestEpics
    ID: Basler-a2A1920-51gcBAS-40204275
    CLASS: Basler-a2A2600-20gmBAS

  - type: ADCore.NDPvaPlugin
    PORT: TestEpics.PVA
    PVNAME: "SPARC:CAM:TestEpics:PVA:OUTPUT"
    P: "SPARC:CAM:TestEpics"
    R: ":Pva1:"
    NDARRAY_PORT: TestEpics
    ENABLED: 1

  - type: ADCore.NDStdArrays
    P: "SPARC:CAM:TestEpics"
    R: ":image1:"
    PORT: TestEpics.NTD
    NDARRAY_PORT: TestEpics
    TYPE: "Int16"
    FTVL: USHORT
    NELEMENTS: 325546
    ENABLED: 1

  - type: ADCore.NDFileTIFF
    PORT: TestEpics.TIFF
    NDARRAY_PORT: TestEpics
    P: "SPARC:CAM:TestEpics:"
    R: "TIFF1:"
    ENABLED: 1

  - type: epics.PostStartupCommand
    command: |
      dbpf("SPARC:CAM:TestEpics:TIFF1:FilePath", "__DATA_DIR__")
      dbpf("SPARC:CAM:TestEpics:TIFF1:FileWriteMode",2)
      dbpf("SPARC:CAM:TestEpics:TIFF1:FileTemplate","%s%s_%3.3d.tiff")

  - type: ADAravis.aravisCamera
    P: "SPARC:CAM:"
    R: "AC1CAM01:"
    PORT: AC1CAM01
    ID: Basler-scA640-70gm-21273723
    CLASS: Basler-scA640-70gm
    TIMEOUT: 5

  - type: ADCore.NDPvaPlugin
    PORT: AC1CAM01.PVA
    PVNAME: "SPARC:CAM:AC1CAM01:PVA:OUTPUT"
    P: "SPARC:CAM:AC1CAM01"
    R: ":Pva1:"
    NDARRAY_PORT: AC1CAM01
    ENABLED: 1

  - type: ADCore.NDStdArrays
    P: "SPARC:CAM:AC1CAM01"
    R: ":image1:"
    PORT: AC1CAM01.NTD
    NDARRAY_PORT: AC1CAM01
    TYPE: "Int16"
    FTVL: USHORT
    NELEMENTS: 325546
    ENABLED: 1

  - type: ADCore.NDFileTIFF
    PORT: AC1CAM01.TIFF
    NDARRAY_PORT: AC1CAM01
    P: "SPARC:CAM:AC1CAM01:"
    R: "TIFF1:"
    ENABLED: 1

  - type: epics.PostStartupCommand
    command: |
      dbpf("SPARC:CAM:AC1CAM01:TIFF1:FilePath", "__DATA_DIR__")
      dbpf("SPARC:CAM:AC1CAM01:TIFF1:FileWriteMode",2)
      dbpf("SPARC:CAM:AC1CAM01:TIFF1:FileTemplate","%s%s_%3.3d.tiff")

  - type: ADAravis.aravisCamera
    P: "SPARC:CAM:"
    R: "THVCAM01:"
    PORT: THVCAM01
    ID: Basler-scA640-70gm-21290809
    CLASS: Basler-scA640-70gm
    TIMEOUT: 5

  - type: ADCore.NDPvaPlugin
    PORT: THVCAM01.PVA
    PVNAME: "SPARC:CAM:THVCAM01:PVA:OUTPUT"
    P: "SPARC:CAM:THVCAM01"
    R: ":Pva1:"
    NDARRAY_PORT: THVCAM01
    ENABLED: 1

  - type: ADCore.NDStdArrays
    P: "SPARC:CAM:THVCAM01"
    R: ":image1:"
    PORT: THVCAM01.NTD
    NDARRAY_PORT: THVCAM01
    TYPE: "Int16"
    FTVL: USHORT
    NELEMENTS: 325546
    ENABLED: 1

  - type: ADCore.NDFileTIFF
    PORT: THVCAM01.TIFF
    NDARRAY_PORT: THVCAM01
    P: "SPARC:CAM:THVCAM01:"
    R: "TIFF1:"
    ENABLED: 1

  - type: epics.PostStartupCommand
    command: |
      dbpf("SPARC:CAM:THVCAM01:TIFF1:FilePath", "__DATA_DIR__")
      dbpf("SPARC:CAM:THVCAM01:TIFF1:FileWriteMode",2)
      dbpf("SPARC:CAM:THVCAM01:TIFF1:FileTemplate","%s%s_%3.3d.tiff")

  - type: ADAravis.aravisCamera
    P: "SPARC:CAM:"
    R: "UTLCAM01:"
    PORT: UTLCAM01
    ID: Basler-scA640-70gm-21732890
    CLASS: Basler-scA640-70gm
    TIMEOUT: 5

  - type: ADCore.NDPvaPlugin
    PORT: UTLCAM01.PVA
    PVNAME: "SPARC:CAM:UTLCAM01:PVA:OUTPUT"
    P: "SPARC:CAM:UTLCAM01"
    R: ":Pva1:"
    NDARRAY_PORT: UTLCAM01
    ENABLED: 1

  - type: ADCore.NDStdArrays
    P: "SPARC:CAM:UTLCAM01"
    R: ":image1:"
    PORT: UTLCAM01.NTD
    NDARRAY_PORT: UTLCAM01
    TYPE: "Int16"
    FTVL: USHORT
    NELEMENTS: 325546
    ENABLED: 1

  - type: ADCore.NDFileTIFF
    PORT: UTLCAM01.TIFF
    NDARRAY_PORT: UTLCAM01
    P: "SPARC:CAM:UTLCAM01:"
    R: "TIFF1:"
    ENABLED: 1

  - type: epics.PostStartupCommand
    command: |
      dbpf("SPARC:CAM:UTLCAM01:TIFF1:FilePath", "__DATA_DIR__")
      dbpf("SPARC:CAM:UTLCAM01:TIFF1:FileWriteMode",2)
      dbpf("SPARC:CAM:UTLCAM01:TIFF1:FileTemplate","%s%s_%3.3d.tiff")

  - type: ADAravis.aravisCamera
    P: "SPARC:CAM:"
    R: "PLVCAM02:"
    PORT: PLVCAM02
    ID: Basler-scA640-70gm-21732894
    CLASS: Basler-scA640-70gm
    TIMEOUT: 5

  - type: ADCore.NDPvaPlugin
    PORT: PLVCAM02.PVA
    PVNAME: "SPARC:CAM:PLVCAM02:PVA:OUTPUT"
    P: "SPARC:CAM:PLVCAM02"
    R: ":Pva1:"
    NDARRAY_PORT: PLVCAM02
    ENABLED: 1

  - type: ADCore.NDStdArrays
    P: "SPARC:CAM:PLVCAM02"
    R: ":image1:"
    PORT: PLVCAM02.NTD
    NDARRAY_PORT: PLVCAM02
    TYPE: "Int16"
    FTVL: USHORT
    NELEMENTS: 325546
    ENABLED: 1

  - type: ADCore.NDFileTIFF
    PORT: PLVCAM02.TIFF
    NDARRAY_PORT: PLVCAM02
    P: "SPARC:CAM:PLVCAM02:"
    R: "TIFF1:"
    ENABLED: 1

  - type: epics.PostStartupCommand
    command: |
      dbpf("SPARC:CAM:PLVCAM02:TIFF1:FilePath", "__DATA_DIR__")
      dbpf("SPARC:CAM:PLVCAM02:TIFF1:FileWriteMode",2)
      dbpf("SPARC:CAM:PLVCAM02:TIFF1:FileTemplate","%s%s_%3.3d.tiff")

  - type: ADAravis.aravisCamera
    P: "SPARC:CAM:"
    R: "AC2CAM01:"
    PORT: AC2CAM01
    ID: Basler-scA640-70gm-21732900
    CLASS: Basler-scA640-70gm
    TIMEOUT: 5

  - type: ADCore.NDPvaPlugin
    PORT: AC2CAM01.PVA
    PVNAME: "SPARC:CAM:AC2CAM01:PVA:OUTPUT"
    P: "SPARC:CAM:AC2CAM01"
    R: ":Pva1:"
    NDARRAY_PORT: AC2CAM01
    ENABLED: 1

  - type: ADCore.NDStdArrays
    P: "SPARC:CAM:AC2CAM01"
    R: ":image1:"
    PORT: AC2CAM01.NTD
    NDARRAY_PORT: AC2CAM01
    TYPE: "Int16"
    FTVL: USHORT
    NELEMENTS: 325546
    ENABLED: 1

  - type: ADCore.NDFileTIFF
    PORT: AC2CAM01.TIFF
    NDARRAY_PORT: AC2CAM01
    P: "SPARC:CAM:AC2CAM01:"
    R: "TIFF1:"
    ENABLED: 1

  - type: epics.PostStartupCommand
    command: |
      dbpf("SPARC:CAM:AC2CAM01:TIFF1:FilePath", "__DATA_DIR__")
      dbpf("SPARC:CAM:AC2CAM01:TIFF1:FileWriteMode",2)
      dbpf("SPARC:CAM:AC2CAM01:TIFF1:FileTemplate","%s%s_%3.3d.tiff")

  - type: ADAravis.aravisCamera
    P: "SPARC:CAM:"
    R: "DGLCAM00:"
    PORT: DGLCAM00
    ID: Basler-scA640-70gm-23665716
    CLASS: Basler-scA640-70gm
    TIMEOUT: 5

  - type: ADCore.NDPvaPlugin
    PORT: DGLCAM00.PVA
    PVNAME: "SPARC:CAM:DGLCAM00:PVA:OUTPUT"
    P: "SPARC:CAM:DGLCAM00"
    R: ":Pva1:"
    NDARRAY_PORT: DGLCAM00
    ENABLED: 1

  - type: ADCore.NDStdArrays
    P: "SPARC:CAM:DGLCAM00"
    R: ":image1:"
    PORT: DGLCAM00.NTD
    NDARRAY_PORT: DGLCAM00
    TYPE: "Int16"
    FTVL: USHORT
    NELEMENTS: 325546
    ENABLED: 1

  - type: ADCore.NDFileTIFF
    PORT: DGLCAM00.TIFF
    NDARRAY_PORT: DGLCAM00
    P: "SPARC:CAM:DGLCAM00:"
    R: "TIFF1:"
    ENABLED: 1

  - type: epics.PostStartupCommand
    command: |
      dbpf("SPARC:CAM:DGLCAM00:TIFF1:FilePath", "__DATA_DIR__")
      dbpf("SPARC:CAM:DGLCAM00:TIFF1:FileWriteMode",2)
      dbpf("SPARC:CAM:DGLCAM00:TIFF1:FileTemplate","%s%s_%3.3d.tiff")

  - type: ADAravis.aravisCamera
    P: "SPARC:CAM:"
    R: "GUNCAM01:"
    PORT: GUNCAM01
    ID: Basler-scA640-70gm-23665718
    CLASS: Basler-scA640-70gm
    TIMEOUT: 5

  - type: ADCore.NDPvaPlugin
    PORT: GUNCAM01.PVA
    PVNAME: "SPARC:CAM:GUNCAM01:PVA:OUTPUT"
    P: "SPARC:CAM:GUNCAM01"
    R: ":Pva1:"
    NDARRAY_PORT: GUNCAM01
    ENABLED: 1

  - type: ADCore.NDStdArrays
    P: "SPARC:CAM:GUNCAM01"
    R: ":image1:"
    PORT: GUNCAM01.NTD
    NDARRAY_PORT: GUNCAM01
    TYPE: "Int16"
    FTVL: USHORT
    NELEMENTS: 325546
    ENABLED: 1

  - type: ADCore.NDFileTIFF
    PORT: GUNCAM01.TIFF
    NDARRAY_PORT: GUNCAM01
    P: "SPARC:CAM:GUNCAM01:"
    R: "TIFF1:"
    ENABLED: 1

  - type: epics.PostStartupCommand
    command: |
      dbpf("SPARC:CAM:GUNCAM01:TIFF1:FilePath", "__DATA_DIR__")
      dbpf("SPARC:CAM:GUNCAM01:TIFF1:FileWriteMode",2)
      dbpf("SPARC:CAM:GUNCAM01:TIFF1:FileTemplate","%s%s_%3.3d.tiff")

  - type: ADAravis.aravisCamera
    P: "SPARC:CAM:"
    R: "PLVCAM01:"
    PORT: PLVCAM01
    ID: Basler-scA640-74gm-21002010
    CLASS: Basler-scA640-70gm
    TIMEOUT: 5

  - type: ADCore.NDPvaPlugin
    PORT: PLVCAM01.PVA
    PVNAME: "SPARC:CAM:PLVCAM01:PVA:OUTPUT"
    P: "SPARC:CAM:PLVCAM01"
    R: ":Pva1:"
    NDARRAY_PORT: PLVCAM01
    ENABLED: 1

  - type: ADCore.NDStdArrays
    P: "SPARC:CAM:PLVCAM01"
    R: ":image1:"
    PORT: PLVCAM01.NTD
    NDARRAY_PORT: PLVCAM01
    TYPE: "Int16"
    FTVL: USHORT
    NELEMENTS: 325546
    ENABLED: 1

  - type: ADCore.NDFileTIFF
    PORT: PLVCAM01.TIFF
    NDARRAY_PORT: PLVCAM01
    P: "SPARC:CAM:PLVCAM01:"
    R: "TIFF1:"
    ENABLED: 1

  - type: epics.PostStartupCommand
    command: |
      dbpf("SPARC:CAM:PLVCAM01:TIFF1:FilePath", "__DATA_DIR__")
      dbpf("SPARC:CAM:PLVCAM01:TIFF1:FileWriteMode",2)
      dbpf("SPARC:CAM:PLVCAM01:TIFF1:FileTemplate","%s%s_%3.3d.tiff")

  - type: ADAravis.aravisCamera
    P: "SPARC:CAM:"
    R: "UTLCAM02:"
    PORT: UTLCAM02
    ID: Basler-scA640-74gm-21290828
    CLASS: Basler-scA640-70gm
    TIMEOUT: 5

  - type: ADCore.NDPvaPlugin
    PORT: UTLCAM02.PVA
    PVNAME: "SPARC:CAM:UTLCAM02:PVA:OUTPUT"
    P: "SPARC:CAM:UTLCAM02"
    R: ":Pva1:"
    NDARRAY_PORT: UTLCAM02
    ENABLED: 1

  - type: ADCore.NDStdArrays
    P: "SPARC:CAM:UTLCAM02"
    R: ":image1:"
    PORT: UTLCAM02.NTD
    NDARRAY_PORT: UTLCAM02
    TYPE: "Int16"
    FTVL: USHORT
    NELEMENTS: 325546
    ENABLED: 1

  - type: ADCore.NDFileTIFF
    PORT: UTLCAM02.TIFF
    NDARRAY_PORT: UTLCAM02
    P: "SPARC:CAM:UTLCAM02:"
    R: "TIFF1:"
    ENABLED: 1

  - type: epics.PostStartupCommand
    command: |
      dbpf("SPARC:CAM:UTLCAM02:TIFF1:FilePath", "__DATA_DIR__")
      dbpf("SPARC:CAM:UTLCAM02:TIFF1:FileWriteMode",2)
      dbpf("SPARC:CAM:UTLCAM02:TIFF1:FileTemplate","%s%s_%3.3d.tiff")

  - type: ADAravis.aravisCamera
    P: "SPARC:CAM:"
    R: "OSCAM02:"
    PORT: OSCAM02
    ID: Basler-scA640-74gm-21290841
    CLASS: Basler-scA640-70gm
    TIMEOUT: 5

  - type: ADCore.NDPvaPlugin
    PORT: OSCAM02.PVA
    PVNAME: "SPARC:CAM:OSCAM02:PVA:OUTPUT"
    P: "SPARC:CAM:OSCAM02"
    R: ":Pva1:"
    NDARRAY_PORT: OSCAM02
    ENABLED: 1

  - type: ADCore.NDStdArrays
    P: "SPARC:CAM:OSCAM02"
    R: ":image1:"
    PORT: OSCAM02.NTD
    NDARRAY_PORT: OSCAM02
    TYPE: "Int16"
    FTVL: USHORT
    NELEMENTS: 325546
    ENABLED: 1

  - type: ADCore.NDFileTIFF
    PORT: OSCAM02.TIFF
    NDARRAY_PORT: OSCAM02
    P: "SPARC:CAM:OSCAM02:"
    R: "TIFF1:"
    ENABLED: 1

  - type: epics.PostStartupCommand
    command: |
      dbpf("SPARC:CAM:OSCAM02:TIFF1:FilePath", "__DATA_DIR__")
      dbpf("SPARC:CAM:OSCAM02:TIFF1:FileWriteMode",2)
      dbpf("SPARC:CAM:OSCAM02:TIFF1:FileTemplate","%s%s_%3.3d.tiff")

  - type: ADAravis.aravisCamera
    P: "SPARC:CAM:"
    R: "OSCAM01:"
    PORT: OSCAM01
    ID: Basler-scA640-74gm-21751350
    CLASS: Basler-scA640-70gm
    TIMEOUT: 5

  - type: ADCore.NDPvaPlugin
    PORT: OSCAM01.PVA
    PVNAME: "SPARC:CAM:OSCAM01:PVA:OUTPUT"
    P: "SPARC:CAM:OSCAM01"
    R: ":Pva1:"
    NDARRAY_PORT: OSCAM01
    ENABLED: 1

  - type: ADCore.NDStdArrays
    P: "SPARC:CAM:OSCAM01"
    R: ":image1:"
    PORT: OSCAM01.NTD
    NDARRAY_PORT: OSCAM01
    TYPE: "Int16"
    FTVL: USHORT
    NELEMENTS: 325546
    ENABLED: 1

  - type: ADCore.NDFileTIFF
    PORT: OSCAM01.TIFF
    NDARRAY_PORT: OSCAM01
    P: "SPARC:CAM:OSCAM01:"
    R: "TIFF1:"
    ENABLED: 1

  - type: epics.PostStartupCommand
    command: |
      dbpf("SPARC:CAM:OSCAM01:TIFF1:FilePath", "__DATA_DIR__")
      dbpf("SPARC:CAM:OSCAM01:TIFF1:FileWriteMode",2)
      dbpf("SPARC:CAM:OSCAM01:TIFF1:FileTemplate","%s%s_%3.3d.tiff")

  - type: ADAravis.aravisCamera
    P: "SPARC:CAM:"
    R: "AC3CAM01:"
    PORT: AC3CAM01
    ID: Basler-scA640-74gm-21751352
    CLASS: Basler-scA640-70gm
    TIMEOUT: 5

  - type: ADCore.NDPvaPlugin
    PORT: AC3CAM01.PVA
    PVNAME: "SPARC:CAM:AC3CAM01:PVA:OUTPUT"
    P: "SPARC:CAM:AC3CAM01"
    R: ":Pva1:"
    NDARRAY_PORT: AC3CAM01
    ENABLED: 1

  - type: ADCore.NDStdArrays
    P: "SPARC:CAM:AC3CAM01"
    R: ":image1:"
    PORT: AC3CAM01.NTD
    NDARRAY_PORT: AC3CAM01
    TYPE: "Int16"
    FTVL: USHORT
    NELEMENTS: 325546
    ENABLED: 1

  - type: ADCore.NDFileTIFF
    PORT: AC3CAM01.TIFF
    NDARRAY_PORT: AC3CAM01
    P: "SPARC:CAM:AC3CAM01:"
    R: "TIFF1:"
    ENABLED: 1

  - type: epics.PostStartupCommand
    command: |
      dbl  > __CONFIG_DIR__/pvlist.txt           ## dumps PV NAMES
      dbpf("SPARC:CAM:AC3CAM01:TIFF1:FilePath", "__DATA_DIR__")
      dbpf("SPARC:CAM:AC3CAM01:TIFF1:FileWriteMode",2)
      dbpf("SPARC:CAM:AC3CAM01:TIFF1:FileTemplate","%s%s_%3.3d.tiff")

