
ioc_name: menlo
description: menlo devices

entities:

  - type: menlosyncro.device
    controllerName: MSYNCH
    P: "SPARC:MENLO:SYNCTHETA"
    IP:  scsparcmoxa002.lnf.infn.it
    TCPPORT: 4004
    HOSTID: 0
    DEVICEID: 255

  - type: menlolac.device
    controllerName: MLAC
    P: "SPARC:MENLO:LAC"
    IP:  scsparcmoxa002.lnf.infn.it
    TCPPORT: 4001
    HOSTID: 0
    DEVICEID: 255
  
  - type: menlolfc.device
    controllerName: MLFC
    P: "SPARC:MENLO:SYNCOMO"
    IP:  scsparcmoxa002.lnf.infn.it
    TCPPORT: 4003
    HOSTID: 17
    DEVICEID: 66

  - type: epics.PostStartupCommand 
    command: |
          dbl
          dbl  > __CONFIG_DIR__/pvlist.txt           ## dumps PV NAMES
