beamline: eli
namespace: eli
domain: ""
ingressClassName: "haproxy"
epik8namespace: "apps.k8s-da.lnf.infn.it"
targetRevision: "experimental"
serviceAccountName: "default"
## starting point
giturl: https://baltig.infn.it/lnf-da-control/epik8s-eli.git
gitrev: master
baseIp: "10.96.0.0/16" ## valid IPs is 10.96.0.0/12
startIp: 1
openshift: false
epicsConfiguration:
  name: "epics-configuration" # name of existing configMap that set CA parameters
  address_list: "
    gen-cs-gp08-ioc06.lnf.infn.it 
    "

# 10.16.4.26 gen-cs-gp09-ioc01.lnf.infn.it
## modulator
# plelillrf001.lnf.infn.it
# plelillrfs001.lnf.infn.it
# plelillrfs002.lnf.infn.it
# plelillrfc001.lnf.infn.it
# mikelinux.lnf.infn.it 
  max_array_bytes: "10000000"
  # conn_tmo: 120
  services:
    
    gateway:
      charturl: 'https://baltig.infn.it/epics-containers/ca-gateway-chart.git'
      ingress:
        enabled: false
      loadbalancer: 10.10.6.107
      replicaCount: 1
      exec: start.sh
      auto_security: true
      gitinit: true
      autosync: true ## restart automatically on changes
      staticIp: true
      resources:
            limits:
              cpu: 999m
              memory: 4Gi
            requests:
              cpu: 400m
              memory: 1Gi
    pvagateway:
      charturl: 'https://baltig.infn.it/epics-containers/ca-gateway-chart.git'
      image:
        repository: baltig.infn.it:4567/epics-containers/docker-pva-gateway
        tag: "latest"
      ingress:
        enabled: false
      loadbalancer: 10.10.6.108
      replicaCount: 1
      exec: start.sh
      auto_security: true
      gitinit: true
      autosync: true ## restart automatically on changes
      staticIp: true
      resources:
            limits:
              cpu: 999m
              memory: 2Gi
            requests:
              cpu: 400m
              memory: 500Mi
    archiver: 
      charturl: 'https://baltig.infn.it/epics-containers/epics-archiver-chart.git'

      replicaCount: 1
      serviceAccount:
        create: false
        name: "default"
      storage:
        lts:
          path: /storage/lts
          size: 100Gi
          claim: ""
          storageClassName: "nassparc-k8s-quad02"
          accessMode: ReadWriteOnce
        mts:
          path: /storage/mts
          size: 100Gi
          claim: ""
          storageClassName: "nassparc-k8s-quad02"
          accessMode: ReadWriteOnce
        sts:
          path: /storage/sts
          size: 10Gi
          claim: ""
          accessMode: ReadWriteOnce
        logs:
          path: /storage/logs
          size: 50Gi
          claim: ""
          accessMode: ReadWriteOnce
          storageClassName: "nassparc-k8s-quad02"

      mysql:
            host: mysql
            dbname: arcappl
            user: arcappl
            pass: arcappl
      enable_ingress: true
      securityContext:
            privileged: true
            runAsUser: 0
            runAsGroup: 1000
      resources:
            limits:
              cpu: 999m
              memory: 6Gi
            requests:
              cpu: 100m
              memory: 4Gi
      autosync: true ## restart automatically on changes
      usegateway: true

    console: 
        replicaCount: 1
        charturl: https://baltig.infn.it/epics-containers/epics-console-chart.git
        enable_ingress: true
        gitpath: opi
        resources:
            limits:
              cpu: 2000m
              memory: 4Gi
            requests:
              cpu: 1000m
              memory: 1Gi
        gitRepoConfig:
          url: https://baltig.infn.it/lnf-da-control/epik8s-eli.git
          path: opi
          branch: master
        autosync: true ## restart automatically on changes
        usegateway: true

    notebook: 
      charturl: 'https://baltig.infn.it/epics-containers/jupyter-control-notebook-chart.git'
      replicaCount: 1
      gitRepoConfig:
        url: https://baltig.infn.it/lnf-da-control/ecs-jupyter-control.git
        path: .
        branch: main
        init: true
      dataVolume:
          claim:  ## an existing claim or empty will create a new one
          size: 5Gi ## size of the claim
          accessMode: ReadWriteOnce
      enable_ingress: true
      usegateway: true
      autosync: true ## restart automatically on changes
      pip:
        - bluesky
        - infn-ophyd-hal
  

    webalarm: 
      loglevel: DEBUG
      charturl: https://baltig.infn.it/epics-containers/phoebus-services-chart.git
      image:
        repository: baltig.infn.it:4567/epics-containers/phoebus-web-docker
      phoebusservice: "webalarm"
      auto_security: true
      enable_ingress: true
      autosync: true ## restart automatically on changes
      service:
        loglevel: "INFO"
      usegateway: true

    pws: 
      loglevel: DEBUG
      charturl: https://baltig.infn.it/epics-containers/phoebus-services-chart.git
      image:
        repository: baltig.infn.it:4567/epics-containers/phoebus-web-docker
      phoebusservice: "pvws"
      auto_security: true
      enable_ingress: true
      autosync: true ## restart automatically on changes
      service:
        loglevel: "INFO"
      usegateway: true
    
    dbwr: 
      loglevel: DEBUG
      charturl: https://baltig.infn.it/epics-containers/phoebus-services-chart.git
      image:
        repository: baltig.infn.it:4567/epics-containers/phoebus-web-docker
      phoebusservice: "dbwr"
      auto_security: true
      enable_ingress: true
      autosync: true ## restart automatically on changes
      service:
        loglevel: "INFO"
      usegateway: true
      gitRepoConfig:
          url: https://baltig.infn.it/lnf-da-control/eli-epics-opi.git
          path: .
      pvws:
        host: eli-pws.apps.okd-datest.lnf.infn.it
        port: 80
    

    olog: 
      loglevel: DEBUG
      charturl: https://baltig.infn.it/epics-containers/phoebus-services-chart.git
      phoebusservice: "olog"
      auto_security: true
      enable_ingress: true
      mongodb: "eli-ologAttachments"
      autosync: true ## restart automatically on changes
      service:
        loglevel: "INFO"
      usegateway: true

    saveandrestore: 
      loglevel: DEBUG
      charturl: https://baltig.infn.it/epics-containers/phoebus-services-chart.git
      phoebusservice: "saveandrestore"
      auto_security: true
      enable_ingress: true
      mongodb: "eli-saveandrestore"
      autosync: true ## restart automatically on changes
      service:
        loglevel: "DEBUG"
    alarmserver: 
      loglevel: DEBUG
      charturl: https://baltig.infn.it/epics-containers/phoebus-services-chart.git
      phoebusservice: "alarmserver"
      auto_security: true
      enable_ingress: true
      mongodb: "eli-ologAttachments"
      # alarm:
      #  config: "Accelerator,AcceleratorCommand,AcceleratorTalk"
      gitinit: true
      autosync: true ## restart automatically on changes
      usegateway: true

    alarmlogger: 
      loglevel: DEBUG
      charturl: https://baltig.infn.it/epics-containers/phoebus-services-chart.git
      phoebusservice: "alarmlogger"
      auto_security: true
      enable_ingress: true
      mongodb: "eli-ologAttachments"
      alarm:
        config: "Accelerator"
        topics: "Accelerato,ALARM,CONFIGS"
      autosync: true ## restart automatically on changes

    channelfinder: 
      autosync: true ## restart automatically on changes
      loglevel: DEBUG
      charturl: https://baltig.infn.it/epics-containers/channelfinder-chart.git
      auto_security: true
      enable_ingress: true
      mongodb: "eli-channelfinder"
      aa:
        urls: "{'default': 'http://eli-archiver.apps.okd-datest.lnf.infn.it'}"
        default_alias: default
        enabled: true
        pva: false
        archive_property_name: archive
        archiver_property_name: archiver
        auto_pause: pvStatus,archive

    scanserver: 
      loglevel: DEBUG
      charturl: https://baltig.infn.it/epics-containers/phoebus-services-chart.git
      phoebusservice: "scanserver"
      auto_security: true
      enable_ingress: true
      mongodb: "eli-ologAttachments"
    mysql: 
      name: mysql
      charturl: registry-1.docker.io/bitnamicharts
      targetRevision: '9.21.1'
      chart: mysql
      auth:
          rootPassword: "arcappl"
          createDatabase: true
          database: "arcappl"
          username: "arcappl"
          password: "arcappl"
      serviceAccount:
        create: false
        name: "default"
  
  iocs:
    - name: "llrf01"
      asset: "https://confluence.infn.it/x/doKBBg"
      charturl: 'https://baltig.infn.it/epics-containers/ioc-launcher-chart.git'
      iocdir: "libera-llrf"
      devtype: llrf
      devgroup: rf
      iocprefix: "LEL-RF-LLRF03"
      host: "10.16.4.31" # "plelillrf001"
      scpoptions: "-O"
      ssh_options: "-o PubkeyAcceptedKeyTypes=+ssh-rsa"
      workdir: "/opt/epik8s-eli"
      exec: "st.cmd"
      #autosync: true ## restart automatically on changes

    - name: "orbit"
      asset: "https://confluence.infn.it/x/nYD8DQ"
      charturl: 'https://baltig.infn.it/epics-containers/ioc-chart.git'
      image: baltig.infn.it:4567/epics-containers/epics-py-base
      iocprefix: "LEL:ORBIT"
      devtype: softioc
      devgroup: diag
      start: "/epics/ioc/config/start.sh"
      gitinit: true
      autosync: true ## restart automatically on changes
      usegateway: false
    
    
    - name: "ibilt-test"
      asset: "https://confluence.infn.it/x/nYD8DQ"
      devtype: mag
      devgroup: magnets
      charturl: 'https://baltig.infn.it/epics-containers/ioc-chart.git'
      image: baltig.infn.it:4567/epics-containers/infn-epics-ioc:2.30b5
      gitinit: true
      autosync: false ## restart automatically on changes
      # carepeater: true ## launch ca repeater, this ioc needs it

    - name: "sigmaphi-test"
      asset: "https://confluence.infn.it/x/nYD8DQ"
      devtype: mag
      devgroup: magnets
      charturl: 'https://baltig.infn.it/epics-containers/ioc-chart.git'
      image: baltig.infn.it:4567/epics-containers/infn-epics-ioc:2.30b5
      gitinit: true
      autosync: false ## restart automatically on changes
      # carepeater: true ## launch ca repeater, this ioc needs it

  
    - name: "cam01"
      asset: "https://servicedesk.infn.it/secure/ObjectSchema.jspa?id=44&typeId=2748&objectId=126655"
      charturl: 'https://baltig.infn.it/epics-containers/ioc-chart.git'
      image: baltig.infn.it:4567/epics-containers/infn-epics-ioc:latest
      devtype: camera
      devgroup: diag
      gitinit: true
      iocdir: "camera"
      pva: true
      networks:
        - name: "gigevision-client"
          annotation: "gigevision-network"
      # hostNetwork: true
      useAffinity: true
      affinityKey: "gige"
      affinityValue: "enabled"
      iocprefix: "LEL:SCN01"
      iocroot: "CAM01"
      autosync: true ## restart automatically on changes
      iocinit:
        - name: "AcquirePeriod"
          value: "1"
        - name: "FrameRate"
          value: "1"
        - name: "FrameRateEnable"
          value: "Yes"
      iocparam:
      - name: "CAMERA_ID"
        value: "Basler-a2A1920-51gmBAS-40458493"
      - name: "CAMERA_CLASS"
        value: "Basler-a2A2600-20gmBAS"
      - name: "CAMERA_TYPE"
        value: "Int8"
      - name: "CAMERA_FTVL"
        value: "UCHAR"
      - name: "CAMERA_ELEMS"
        value: "325546"
      - name: "CAMERA_STATS_XSIZE"
        value: "1024"
      - name: "CAMERA_STATS_YSIZE"
        value: "768" 

    - name: "cam02"
      asset: "https://servicedesk.infn.it/secure/ObjectSchema.jspa?id=44&typeId=2748&objectId=126656"
      charturl: 'https://baltig.infn.it/epics-containers/ioc-chart.git'
      image: baltig.infn.it:4567/epics-containers/infn-epics-ioc:latest
      devtype: camera
      devgroup: diag
      gitinit: true
      iocdir: "camera"
      pva: true
      networks:
        - name: "gigevision-client"
          annotation: "gigevision-network"
      # hostNetwork: true
      useAffinity: true
      affinityKey: "gige"
      affinityValue: "enabled"
      iocprefix: "LEL:SCN02"
      iocroot: "CAM01"
      autosync: true ## restart automatically on changes
      iocinit:
        - name: "AcquirePeriod"
          value: "1"
        - name: "FrameRate"
          value: "1"
        - name: "FrameRateEnable"
          value: "Yes"
      iocparam:
      - name: "CAMERA_ID"
        value: "Basler-a2A1920-51gmBAS-40458497"
      - name: "CAMERA_CLASS"
        value: "Basler-a2A2600-20gmBAS"
      - name: "CAMERA_TYPE"
        value: "Int8"
      - name: "CAMERA_FTVL"
        value: "UCHAR"
      - name: "CAMERA_ELEMS"
        value: "325546"
      - name: "CAMERA_STATS_XSIZE"
        value: "1024"
      - name: "CAMERA_STATS_YSIZE"
        value: "768"

    - name: "cam03"
      asset: "https://servicedesk.infn.it/secure/ObjectSchema.jspa?id=44&typeId=2748&objectId=126656"
      charturl: 'https://baltig.infn.it/epics-containers/ioc-chart.git'
      image: baltig.infn.it:4567/epics-containers/infn-epics-ioc:latest
      devtype: camera
      devgroup: diag
      gitinit: true
      iocdir: "camera"
      pva: true
      networks:
        - name: "gigevision-client"
          annotation: "gigevision-network"
      # hostNetwork: true
      useAffinity: true
      affinityKey: "gige"
      affinityValue: "enabled"
      iocprefix: "LEL:SCN03"
      iocroot: "CAM01"
      autosync: true ## restart automatically on changes
      iocinit:
        - name: "AcquirePeriod"
          value: "1"
        - name: "FrameRate"
          value: "1"
        - name: "FrameRateEnable"
          value: "Yes"
      iocparam:
      - name: "CAMERA_ID"
        value: "Basler-a2A1920-51gmBAS-40458491"
      - name: "CAMERA_CLASS"
        value: "Basler-a2A2600-20gmBAS"
      - name: "CAMERA_TYPE"
        value: "Int8"
      - name: "CAMERA_FTVL"
        value: "UCHAR"
      - name: "CAMERA_ELEMS"
        value: "325546"
      - name: "CAMERA_STATS_XSIZE"
        value: "1024"
      - name: "CAMERA_STATS_YSIZE"
        value: "768"

    - name: "cam-sim01"
      asset: "https://confluence.infn.it/x/nYD8DQ"
      charturl: 'https://baltig.infn.it/epics-containers/ioc-chart.git'
      iocdir: "camera-sim"
      autosync: true ## restart automatically on changes
      devtype: camera
      gitinit: true
      pva: true
      devgroup: diag
      iocprefix: "LEL"
      iocroot: "TST01"
      iocinit:
        - name: "AcquirePeriod"
          value: "1"
        - name: "Gain"
          value: "255"
        - name: "SimMode"
          value: "Peaks"
        - name: "PeakStartX"
          value: "250"
        - name: "PeakStartY"
          value: "200"
        - name: "PeakWidthX"
          value: "70"
        - name: "PeakWidthY"
          value: "50"
        - name: "PeakVariation"
          value: "10"
      iocparam:
        - name: "CAMERA_TYPE"
          value: "Int8"
        - name: "CAMERA_FTVL"
          value: "UCHAR"
        - name: "CAMERA_ELEMS"
          value: "325546"
        - name: "CAMERA_STATS_XSIZE"
          value: "1024"
        - name: "CAMERA_STATS_YSIZE"
          value: "768"

    - name: "mrf01-gp09"
      asset: "https://confluence.infn.it/x/nYD8DQ"
      charturl: 'https://baltig.infn.it/epics-containers/ioc-launcher-chart.git'
      iocprefix: "TMG"
      devtype: timing
      devgroup: timing
      host: "10.16.4.24"
      workdir: "/opt/codac-4.1/apps/elinp-gp09-ioc01/iocBoot/epik8s"
      exec: "start.sh"
      autosync: false
      iocparam:
        - name: "EVR_PREFIX"
          value: "EVR01"
        - name: "EVG_PREFIX"
          value: "EVG01"
      ssh_options: "-o HostKeyAlgorithms=ssh-rsa -o PubkeyAcceptedKeyTypes=+ssh-rsa"
      scpoptions: "-O"

    - name: "polrev-icpdas01"
      asset: "https://confluence.infn.it/x/nYD8DQ"
      charturl: 'https://baltig.infn.it/epics-containers/ioc-chart.git'
      iocprefix: "LEL:POLREV"
      iocroot: "ICPDAS01"
      iocdir: "icp7060"
      devtype: icpdas7060
      devgroup: polarity_reversal
      autosync: true
      gitinit: true
      iocparam:
        - name: "__SERVER__"
          value: ddeliicp6r6i001.lnf.infn.it

    - name: "polrev-icpdas02"
      asset: "https://confluence.infn.it/x/nYD8DQ"
      charturl: 'https://baltig.infn.it/epics-containers/ioc-chart.git'
      iocprefix: "LEL:POLREV"
      iocroot: "ICPDAS02"
      iocdir: "icp7060"
      devtype: icpdas7060
      devgroup: polarity_reversal
      autosync: true
      gitinit: true
      iocparam:
        - name: "__SERVER__"
          value: ddeliicp6r6i002.lnf.infn.it

    - name: "mag-wrapper"
      asset: "https://confluence.infn.it/display/SCS/Magnet+SoftIOC+Devil+Wrapper"
      charturl: 'https://baltig.infn.it/epics-containers/ioc-chart.git'
      image: baltig.infn.it:4567/epics-containers/epics-py-base
      iocprefix: "LEL:MAG"
      start: "/epics/ioc/config/start.sh" ## if your mynewioc has a start.sh this line must be kept
      devtype: softioc
      devgroup: mag
      gitinit: true
      autosync: true ## restart automatically on changes
      
cronjobs:
    - name: "chfeeder"
      image: baltig.infn.it:4567/epics-containers/epics-py-base
      schedule: "* */12 * * *" # every 5 min ## "0 */12 * * *" ## at 12
      gitRepoApp:
        url: "https://baltig.infn.it/infn-epics/channelfinder-service-feeder.git"
        path: .
        branch: main
      gitinit: true
      
applications:
    - name: "icpdastemp01"
      image:
        repository: baltig.infn.it:4567/epics-containers/epics-py-base
        tag: "latest"
      namespace: "simulator"
      gitRepoApp:
        url: "https://baltig.infn.it/chaos-lnf-control/py-modbus-device-simulator.git"
        path: .
        branch: main
      gitinit: true
      exec: "pip install --user $USER -r /app/requirements.txt;python /app/modbusDeviceSimulator.py -p 5020 -d icpconet72xx -c /config/config.json"
      service:
        type: ClusterIP
        ports:
          - name: modbusport
            port: 502
            targetport: 5020
            targetname: modbusport
            protocol: TCP
      securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
      

backend:
  namespace: "backend"
  mongo:
    host: mongodb
    port: 27017
    user:
    pwd:
  elasticsearch:
    host: elasticsearch
    clusterName: elasticsearch
    port: 9200
  kafka:
    host: kafka-headless
    port: 9092

syncPolicy:
    automated:
      prune: true  # Optional: Automatically remove resources not specified in Helm chart
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
      - Prune=true

nfsMounts:
    - name: data
      server: 192.168.197.157
      path: /data_epik8s/eli/data
      mountPath: /nfs/data
      opt: "-o nolock"
    - name: autosave
      server: 192.168.197.157
      path: /data_epik8s/eli/autosave
      mountPath: /nfs/autosave
      opt: "-o nolock"
    - name: config
      server: 192.168.197.157
      path: /data_epik8s/eli/config
      mountPath: /nfs/config
      opt: "-o nolock"
    