# yaml-language-server: $schema=../schemas/technosoft.ibek.ioc.schema.json

ioc_name: tmlch3
description: tmlch3

shared:
  - &motor
    type: motorTML.motorAxis
    controller: TML
    NSTEPS: 200
    NMICROSTEPS: 256
    VELO: 20
    VELO_MAX: 50
    VELO_MIN: 0.1
    ACCL: 0.5
    ACCL_MAX: 1.5
    ACCL_MIN: 0.01
    HAR: 0.5
    HVEL: 10
    JAR: 1
    JVEL: 5
    EGU: "ustep"
    SLSP: 0.8
    ENABLED: 1
    TIMEOUT: 0

entities:
  - type: motorTML.CreateController
    controllerName: TML
    P: "SPARC:TML:CH3"
    TTY: /var/tmp/ttyV0
    numAxes: 3
    hostid: 3

  - <<: *motor
    axid: 7
    name: RFDATT01

  - <<: *motor
    axid: 8
    name: RFDPHS01

  - <<: *motor
    axid: 3
    name: W2BPHS01

  - type: epics.PostStartupCommand 
    command: |
          dbl
