# yaml-language-server: $schema=../schemas/technosoft.ibek.ioc.schema.json

ioc_name: tmlch1
description: tmlch1

shared:
  - &motor
    type: motorTML.motorAxis
    controller: TML
    NSTEPS: 200
    NMICROSTEPS: 256
    VELO: 20
    VELO_MAX: 50
    VELO_MIN: 0.1
    ACCL: 0.5
    ACCL_MAX: 1.5
    ACCL_MIN: 0.01
    HAR: 0.5
    HVEL: 10
    JAR: 1
    JVEL: 5
    EGU: "ustep"
    SLSP: 0.8
    ENABLED: 1
    TIMEOUT: 0

entities:
  - type: motorTML.CreateController
    controllerName: TML
    P: "SPARC:TML:CH2"
    TTY: /var/tmp/ttyV0
    numAxes: 11
    hostid: 6

  - <<: *motor
    axid: 2
    name: CMBEOS01

  - <<: *motor
    axid: 8
    name: CMBPLV01
  - <<: *motor
    axid: 5
    name: CMBPQH01

  - <<: *motor
    axid: 4
    name: CMBPQH02
  - <<: *motor
    axid: 6
    name: CMBPQV01
  - <<: *motor
    axid: 7
    name: CMBPQV02
  
  - <<: *motor
    axid: 1
    name: CMBROH01

  - <<: *motor
    axid: 9
    name: CMBROV01

  - <<: *motor
    axid: 10
    name: CMBTHR01

  - <<: *motor
    axid: 3
    name: CMBTHV01

  - <<: *motor
    axid: 255
    name: CMBTRH01

  - type: epics.PostStartupCommand 
    command: |
          
          dbl("*") > __CONFIG_DIR__/pvlist.txt

