# yaml-language-server: $schema=../schemas/ibek.support.schema.json
ioc_name: __IOC_NAME__
description: Camera model with plugins

entities:
  
  - type: ADAravis.aravisCamera
    P: "__IOC_PREFIX__:"
    R: "__IOC_ROOT__:"
    PORT: __IOC_ROOT__
    ID: CAMERA_ID
    CLASS: CAMERA_CLASS

  # Want to have also high throuput PVA protocol
  - type: ADCore.NDPvaPlugin
    PORT: __IOC_ROOT__.PVA
    PVNAME: "__IOC_PREFIX__:__IOC_ROOT__:PVA:OUTPUT"
    P: "__IOC_PREFIX__:__IOC_ROOT__"
    R: ":Pva1:"
    NDARRAY_PORT: __IOC_ROOT__
    ENABLED: 1


  - type: ADCore.NDProcess
    PORT: __IOC_ROOT__.PROC
    P: "__IOC_PREFIX__:__IOC_ROOT__"
    R: ":Proc1:"
    NDARRAY_PORT: __IOC_ROOT__
    ENABLED: 1
  
  - type: ADCore.NDStdArrays
    P: "__IOC_PREFIX__:__IOC_ROOT__"
    R: ":image1:"
    PORT: __IOC_ROOT__.NTD
    NDARRAY_PORT: __IOC_ROOT__
    TYPE: CAMERA_TYPE
    FTVL: CAMERA_FTVL
    NELEMENTS: CAMERA_ELEMS
    ENABLED: 1

  - type: ADCore.NDStats
    PORT: __IOC_ROOT__.STATS
    NDARRAY_PORT: __IOC_ROOT__
    HIST_SIZE: 50
    P: "__IOC_PREFIX__:__IOC_ROOT__"
    R: ":Stats1:"
    XSIZE: CAMERA_STATS_XSIZE
    YSIZE: CAMERA_STATS_YSIZE
    ENABLED: 1

  - type: ADCore.NDFileTIFF
    PORT: __IOC_ROOT__.TIFF
    NDARRAY_PORT: __IOC_ROOT__
    P: "__IOC_PREFIX__:__IOC_ROOT__"
    R: ":TIFF1:"
    ENABLED: 1

  - type: epics.PostStartupCommand 
    command: dbl              ## dumps PV NAMES
    
  - type: epics.EpicsCaMaxArrayBytes 
    max_bytes: 10000000