ioc_name: __IOC_NAME__
description: ICPDAS7060 Control 

entities:

- type: icpdas.icp7060
  NAME: ICPDAS
  IP: __SERVER__
  TCPPORT: 502
  P: __IOC_PREFIX__
  R: __IOC_ROOT__


- type: epics.PostStartupCommand 
  command: |
          dbl("*") > __CONFIG_DIR__/pvlist.txt           ## dumps PV NAMES