uniprefix: "UNISIM"
magnets:
  - HCOR01:
      driver: "sim"
      prefix: "LEL:MAG"
      root: "HCOR01"
      zone: "TM"
      type: "COR"
      desc: "Horizontal Corrector Magnet HCOR01"
      param:
        max: 16.67
        min: -16.67
  - HCOR02:
      driver: "sim"
      prefix: "LEL:MAG"
      root: "HCOR02"
      zone: "TM"
      type: "COR"
      desc: "Horizontal Corrector Magnet HCOR02"
      param:
        max: 16.67
        min: -16.67
  - HCOR03:
      driver: "sim"
      prefix: "LEL:MAG"
      root: "HCOR03"
      zone: "TM"
      type: "COR"
      desc: "Horizontal Corrector Magnet HCOR03"
      param:
        max: 16.67
        min: -16.67
  - HCOR04:
      driver: "sim"
      prefix: "LEL:MAG"
      root: "HCOR04"
      zone: "TM"
      type: "COR"
      desc: "Horizontal Corrector Magnet HCOR04"
      param:
        max: 16.67
        min: -16.67
  - HCOR05:
      driver: "sim"
      prefix: "LEL:MAG"
      root: "HCOR05"
      zone: "TM"
      type: "COR"
      desc: "Horizontal Corrector Magnet HCOR05"
      param:
        max: 16.67
        min: -16.67
  - HCOR06:
      driver: "sim"
      prefix: "LEL:MAG"
      root: "HCOR06"
      zone: "TM"
      type: "COR"
      desc: "Horizontal Corrector Magnet HCOR06"
      param:
        max: 16.67
        min: -16.67
  - HCOR07:
      driver: "sim"
      prefix: "LEL:MAG"
      root: "HCOR07"
      zone: "TM"
      type: "COR"
      desc: "Horizontal Corrector Magnet HCOR07"
      param:
        max: 16.67
        min: -16.67
  - QUAD01:
      driver: "sim"
      prefix: "LEL:MAG"
      root: "QUAD01"
      zone: "TM"
      type: "QUA"
      desc: "Quadrupole Magnet QUAD01"
      param:
        max: 100
        min: -100
  - QUAD02:
      driver: "sim"
      prefix: "LEL:MAG"
      root: "QUAD02"
      zone: "TM"
      type: "QUA"
      desc: "Quadrupole Magnet QUAD02"
      param:
        max: 100
        min: -100
  - QUAD03:
      driver: "sim"
      prefix: "LEL:MAG"
      root: "QUAD03"
      zone: "TM"
      type: "QUA"
      desc: "Quadrupole Magnet QUAD03"
      param:
        max: 100
        min: -100
  - SOL01:
      driver: "sim"
      prefix: "LEL:MAG"
      root: "SOL01"
      zone: "TM"
      type: "SOL"
      desc: "Solenoid Magnet SOL01"
      param:
        max: 500
        min: -500
  - SOL02:
      driver: "sim"
      prefix: "LEL:MAG"
      root: "SOL02"
      zone: "TM"
      type: "SOL"
      desc: "Solenoid Magnet SOL02"
      param:
        max: 500
        min: -500
  - VCOR01:
      driver: "sim"
      prefix: "LEL:MAG"
      root: "VCOR01"
      zone: "TM"
      type: "COR"
      desc: "Vertical Corrector Magnet VCOR01"
      param:
        max: 16.67
        min: -16.67
  - VCOR02:
      driver: "sim"
      prefix: "LEL:MAG"
      root: "VCOR02"
      zone: "TM"
      type: "COR"
      desc: "Vertical Corrector Magnet VCOR02"
      param:
        max: 16.67
        min: -16.67
  - VCOR03:
      driver: "sim"
      prefix: "LEL:MAG"
      root: "VCOR03"
      zone: "TM"
      type: "COR"
      desc: "Vertical Corrector Magnet VCOR03"
      param:
        max: 16.67
        min: -16.67
  - VCOR04:
      driver: "sim"
      prefix: "LEL:MAG"
      root: "VCOR04"
      zone: "TM"
      type: "COR"
      desc: "Vertical Corrector Magnet VCOR04"
      param:
        max: 16.67
        min: -16.67
  - VCOR05:
      driver: "sim"
      prefix: "LEL:MAG"
      root: "VCOR05"
      zone: "TM"
      type: "COR"
      desc: "Vertical Corrector Magnet VCOR05"
      param:
        max: 16.67
        min: -16.67
  - VCOR06:
      driver: "sim"
      prefix: "LEL:MAG"
      root: "VCOR06"
      zone: "TM"
      type: "COR"
      desc: "Vertical Corrector Magnet VCOR06"
      param:
        max: 16.67
        min: -16.67
  - VCOR07:
      driver: "sim"
      prefix: "LEL:MAG"
      root: "VCOR07"
      zone: "TM"
      type: "COR"
      desc: "Vertical Corrector Magnet VCOR07"
      param:
        max: 16.67
        min: -16.67
