apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{.Values.beamline}}-deploy-infra
  namespace: argocd
  labels:
    deploy: {{ .Values.beamline }}
spec:
  project: default
  source:
    repoURL: 'https://baltig.infn.it/epics-containers/epik8s-infra'
    path: .
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
          {{- toYaml .Values | nindent 12 }}

  destination:
    server: 'https://kubernetes.default.svc'
    {{- if .Values.namespace }}
    namespace: {{.Values.namespace}}

    {{- else }}
    namespace: {{.Values.beamline}}
    {{- end}}
  syncPolicy:
    automated:
      prune: true  # Optional: Automatically remove resources not specified in Helm chart
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
      - Prune=true