ioc_name: temp001
description: Modbus Temperature acquisition 

entities:

- type: modbus.modbusDev
  MODBUSPORT: ICPDAS001
  IP: icpdastemp01.simulator
  TCPPORT: 502
  STARTADDR: 0
  DATA_LENGTH: 7
  SERVER_ADDR: 1

- type: modbus.modbusTemp
  PORT: ICPDAS001
  P: "LEL:DIA"
  R: "M1"
  ID: "01"
  DESC: "Temperature PT100 sensor"
  REGOFFSET: 0
  ASLO: 0.00305059
  LOLO: 10
  LOW: 20
  HIGH: 70
  HIHI: 90


- type: modbus.modbusTemp
  PORT: ICPDAS001
  P: "LEL:DIA"
  R: "M1"
  ID: "02"
  DESC: "Temperature PT100 sensor"
  REGOFFSET: 1
  ASLO: 0.00305059
  LOLO: 10
  LOW: 20
  HIGH: 70
  HIHI: 90
